### ISSUE TITLE
CCGT plants are added as OCGT (at least in Spain)

### ISSUE THREAD

**Issue by cristobal-GC** [PyPSA/pypsa-eur#1042]
Power plants initially added to the net show ~25 GW of OCGT in Spain, while all of them are actually CCGT (also in the powerplants.csv file).

The problem could be that the dictionary "carrier_dict" is associating "natural gas" with "OCGT".

https://github.com/PyPSA/pypsa-eur/blob/a18edcc63c407407da5ff37e9a845cd5d1eff42e/scripts/add_electricity.py#L274

In powerplants.csv file, the information corresponding to Spanish CCGT shows "Fueltype: Natural Gas" and "Technology: CCGT".

**Comment by fneum** [comment]
Thanks for pointing this out. Happy to receive your PR.

**Comment by fneum** [comment]
Thanks for reporting! Closed in c89ce9f0
