### ISSUE TITLE
Scenario management: new 'exclude' policy

### ISSUE THREAD

**Issue by lindnemi** [PyPSA/pypsa-eur#1077]
At the moment the scenario management offers three options for sharing resources: sharing nothing, sharing everything up to the electricity network with the option to specify additional  files excluded from sharing('base'), and sharing everything.

I would like to use a further policy which shares everything, except a list of files to be excluded. This is somewhat tricky to implement, since if a single resource file is specified it would be necessary to identify all downstream files that depend on it and exclude them as well.

Perhaps, these downstream files could be obtained from the snakemake object.

**Comment by fneum** [comment]
closed via #1059
