### ISSUE TITLE
ProtectedOutputException in rule retrieve_databundle in file /../../retrieve.smk, line31:

### ISSUE THREAD

**Issue by Naneno1234** [PyPSA/pypsa-eur#1083]
## Checklist

- [x ] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [ x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

If I try to run a Scenario with my edited config I get an Error Message since today. I didnt experience any Problems on prior days. I think it has something to do with the snakemake rule "retrieve databundle". I attached a screenshot of the error message to this ticket. Maybe somebody is able to help me, will be much appreciated!! 

thanks, Max 
![pypsa_bug_LI](https://github.com/PyPSA/pypsa-eur/assets/166618201/f9655a78-db0b-4026-8c49-ddadbf68562b)

**Comment by fneum** [comment]
try adding `--rerun-triggers mtime` to your snakemake call

or set 

```
enable:
  retrieve_databundle: false
  retrieve_cutout: false
```

once you have downloaded the data bundle and cutouts once
