### ISSUE TITLE
Reading in custom_powerplants is brittle

### ISSUE THREAD

**Issue by coroa** [PyPSA/pypsa-eur#109]
Aaah, now I think I get it, that would be tricky. Your `custom_powerplants` file has a `bus` column, hasn't it?

Because, then in `build_powerplants.py`:
```python
def add_custom_powerplants(ppl):
    custom_ppl_query = snakemake.config['electricity']['custom_powerplants']
    if not custom_ppl_query:
        return ppl
    add_ppls = pd.read_csv(snakemake.input.custom_powerplants, index_col=0)
    if isinstance(custom_ppl_query, str):
        add_ppls.query(add_ppls, inplace=True)
    return ppl.append(add_ppls, sort=False)
```
reading in the file will identify this `bus` column as dtype `int` and then when we append will have to extend it to a `float` since it doesn't know what to put for the powerplants in `ppl`.

The fix is to modify it to
```python
def add_custom_powerplants(ppl):
    custom_ppl_query = snakemake.config['electricity']['custom_powerplants']
    if not custom_ppl_query:
        return ppl
    add_ppls = pd.read_csv(snakemake.input.custom_powerplants, index_col=0, dtype={'bus': 'str'})
    if isinstance(custom_ppl_query, str):
        add_ppls.query(custom_ppl_query, inplace=True)
    return ppl.append(add_ppls, sort=False)
```

(Note also that I fixed a second bug in the `add_ppls.query` line).

Can you please add the two fixes to your pull request or another one?

_Originally posted by @coroa in https://github.com/PyPSA/pypsa-eur/pull/103_

**Comment by FabianHofmann** [comment]
ah, tricky...
