### ISSUE TITLE
Missing parameter length_factor in transmission costs update

### ISSUE THREAD

**Issue by cristobal-GC** [PyPSA/pypsa-eur#1095]
Transmission costs are updated at "prepare_network.py", function "set_transmission_limit", but the parameter length factor seems to be missing:

https://github.com/PyPSA/pypsa-eur/blob/180d93951dc8c8b1cca35568f8ed4ca74f5abe42/scripts/prepare_network.py#L178

These transmission costs updates are replacing those previously set at "add_electricity.py", which did considered the length factor:

https://github.com/PyPSA/pypsa-eur/blob/180d93951dc8c8b1cca35568f8ed4ca74f5abe42/scripts/add_electricity.py#L829

**Comment by fneum** [comment]
The length factor is already applied in `cluster_network` and included in `n.links["length"]`, so no additional length factor required.
