### ISSUE TITLE
misplaced technology wildcard in plot_p_nom_max

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#112]
`plot_p_nom_max` has an unneeded wildcard `technology`. This leads to the question should the code either plot 
1. multiple subplots for all renewable resources, then the technology wildcard needs to be deleted or
2. should it plot only one technology which is defined by the wildcard, then the code needs a small revision

_Originally posted by @FabianHofmann in https://github.com/PyPSA/pypsa-eur/pull/107_

**Comment by FabianHofmann** [comment]
[elec_s_cum_p_nom_max_5,full_solar_all.pdf](https://github.com/PyPSA/pypsa-eur/files/3940495/elec_s_cum_p_nom_max_5.full_solar_all.pdf)

**Comment by coroa** [comment]
Yep that looks like it, except for the capacity factors which are strangely high!

**Comment by coroa** [comment]
For each capacity factor you see the total amount of capacity that could be build with this capacity factor or one that is higher. You can think of the blue line to try to approximate the orange line.

**Comment by FabianHofmann** [comment]
> For each capacity factor you see the total amount of capacity that could be build with this capacity factor or one that is higher. You can think of the blue line to try to approximate the orange line.

ah yes, that's a nice plot

> Yep that looks like it, except for the capacity factors which are strangely high!

It is! And I found why, the [end date](https://github.com/PyPSA/pypsa-eur/blob/5143a258acc3437d85139f88e5e314f2378f8fc3/config.tutorial.yaml#L20) in config.tutorial.yaml is at in April 2014 even though the wheather data is provided from march 2013 - april **2013**, and with a the filling values of 1 the averages are strongly shifted. 
@fneum I would interpret this as not intended or?
