### ISSUE TITLE
Path snakemakel.input.hotmaps_industrial_database not correctly mocked

### ISSUE THREAD

**Issue by fhg-isi** [PyPSA/pypsa-eur#1123]
## Describe the Bug

I tried to run 

`python scripts/build_industrial_distribution_key.py`

using

```
        snakemake = mock_snakemake(
            "build_industrial_distribution_key",
            simpl="",
            clusters=37,
        )
```

and got the error below. 

The attribute `snakemakel.input.hotmaps_industrial_database` does not seem to be correctly mocked and 
has the value

`'/home/projekt-resilient03/pypsa-eur/.snakemake/storage/http/gitlab.com/hotmaps/industrial_sites/industrial_sites_Industrial_Database/-/raw/master/data/Industrial_Database.csv'`

## Error Message

Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: '/home/projekt-resilient03/pypsa-eur/.snakemake/storage/http/gitlab.com/hotmaps/industrial_sites/industrial_sites_Industrial_Database/-/raw/master/data/Industrial_Database.csv'
  File "/home/projekt-resilient03/pypsa-eur/scripts/build_industrial_distribution_key.py", line 103, in prepare_hotmaps_database
    df = pd.read_csv(snakemake.input.hotmaps_industrial_database, sep=";", index_col=0)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projekt-resilient03/pypsa-eur/scripts/build_industrial_distribution_key.py", line 189, in <module>
    hotmaps = prepare_hotmaps_database(regions)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/projekt-resilient03/pypsa-eur/.snakemake/storage/http/gitlab.com/hotmaps/industrial_sites/industrial_sites_Industrial_Database/-/raw/master/data/Industrial_Database.csv'

Related:

https://github.com/PyPSA/pypsa-eur/issues/1118

**Comment by fhg-isi** [comment]
I tried to fix the path by adapting `_helpers.py`:

```
def make_accessable(*ios):
            for io in ios:
                for i, _ in enumerate(io):
                    relative_path = io[i]
                    http_prefix = '.snakemake/storage/http/'
                    if relative_path.startswith(http_prefix):
                        absolute_path = relative_path.replace(http_prefix,'http://')
                        io[i] = absolute_path
                    else:
                      io[i] = os.path.abspath(relative_path)
```

Now I get

```
ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "/home/projekt-resilient03/pypsa-eur/scripts/build_industrial_distribution_key.py", line 189, in <module>
    hotmaps = prepare_hotmaps_database(regions)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projekt-resilient03/pypsa-eur/scripts/build_industrial_distribution_key.py", line 120, in prepare_hotmaps_database
    gdf["country"] = gdf.bus.str[:2]
                     ^^^^^^^
  File "/home/projekt-resilient03/conda/envs/pypsa-eur/lib/python3.11/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GeoDataFrame' object has no attribute 'bus'
```

**Comment by fneum** [comment]
This should be fixed now as the HTTPS input is outsourced into a `retrieve*` rule.
