### ISSUE TITLE
AttributeError: 'GeoDataFrame' object has no attribute 'from_country' in build_gas_input_locations.py

### ISSUE THREAD

**Issue by fhg-isi** [PyPSA/pypsa-eur#1126]
## Describe the Bug

When trying to run 

`python scripts/build_gas_input_locations.py`

I get the error below at

```
entry = read_scigrid_gas(entry_fn)
entry["from_country"] = entry.from_country.str.rstrip()
```

The available columns are

```
entry.columns
Index(['name', 'id', 'country_code', 'tags', 'geometry', 0], dtype='object')
```
=> Replace calls like `df.param.apply(pd.Series)`

## Error Message

(pypsa-eur) projekt-resilient03@ubuntu-22-04-lts-temp:~/pypsa-eur$ python scripts/build_gas_input_locations.py
ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "/home/projekt-resilient03/pypsa-eur/scripts/build_gas_input_locations.py", line 171, in <module>
    gas_input_locations = build_gas_input_locations(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/projekt-resilient03/pypsa-eur/scripts/build_gas_input_locations.py", line 110, in build_gas_input_locations
    entry["from_country"] = entry.from_country.str.rstrip()
                            ^^^^^^^^^^^^^^^^^^
  File "/home/projekt-resilient03/conda/envs/pypsa-eur/lib/python3.11/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GeoDataFrame' object has no attribute 'from_country'

Related:

https://github.com/PyPSA/pypsa-eur/issues/1121

https://github.com/PyPSA/pypsa-eur/issues/1125

https://github.com/PyPSA/pypsa-eur/issues/1118

**Comment by martacki** [comment]
until resolved, this can be overcome by downgrading geopandas to 0.14.4, @fhg-isi
