### ISSUE TITLE
Feature request: Multiple custom busmaps compatible with scenario manager

### ISSUE THREAD

**Issue by bobbyxng** [PyPSA/pypsa-eur#1166]
## Describe the feature you'd like to see

Currently, the `cluster_network.py` script takes custom busmaps as an option (https://pypsa-eur.readthedocs.io/en/latest/configuration.html):
> Switch to enable the use of custom busmaps in rule [cluster_network](https://pypsa-eur.readthedocs.io/en/latest/simplification.html#module-cluster_network). If activated the rule looks for provided busmaps at data/custom_busmap_elec_s{simpl}_{clusters}.csv which should have the same format as resources/busmap_elec_s{simpl}_{clusters}.csv, i.e. the index should contain the buses of networks/elec_s{simpl}.nc.

While this may work for the same network in different custom busmap configurations, it is not scalable to running different networks (e.g. when bus ids change across runs). 
--> Proposal to allow for scenario-specific wildcards. E.g. Bus maps could be saved in 
`data/custom_busmaps/{prefix}/{name}/busmap_elec_s{simpl}`

**Comment by fneum** [comment]
I think this is closed. If not, reopen.
