### ISSUE TITLE
Tutorial: Electricity-Only fails; Error in rule simplify_network

### ISSUE THREAD

**Issue by MichaelGeFr** [PyPSA/pypsa-eur#1184]
## Checklist note

- [ yes] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch
- [yes ] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Bug description

When installing the environment based on the environment.yaml given in the latest master branch (2 days since last commit) (conda env create -f envs/environment.yaml)  and executing the sknakemake command (snakemake -call results/test-elec/networks/elec_s_6_ec_lcopt_.nc --configfile config/test/config.electricity.yaml) according to the tutorial I receive the following error.

## Error message

[Wed Jul 31 07:35:08 2024]
Finished job 5.
19 of 24 steps (79%) done
Select jobs to execute...
Execute 1 jobs...

[Wed Jul 31 07:35:08 2024]
localrule simplify_network:
    input: resources/test/networks/elec.nc, resources/test/costs_2030.csv, resources/test/regions_onshore.geojson, resources/test/regions_offshore.geojson
    output: resources/test/networks/elec_s.nc, resources/test/regions_onshore_elec_s.geojson, resources/test/regions_offshore_elec_s.geojson, resources/test/busmap
_elec_s.csv
    log: logs/test/simplify_network/elec_s.log
    jobid: 4
    benchmark: benchmarks/test/simplify_network/elec_s
    reason: Missing output files: resources/test/busmap_elec_s.csv, resources/test/regions_offshore_elec_s.geojson, resources/test/regions_onshore_elec_s.geojson,
resources/test/networks/elec_s.nc; Input files updated by another job: resources/test/networks/elec.nc, resources/test/regions_offshore.geojson, resources/test/cos
ts_2030.csv, resources/test/regions_onshore.geojson
    wildcards: simpl=
    resources: tmpdir=C:\Users\M074F~1.FRA\AppData\Local\Temp\4, mem_mb=12000, mem_mib=11445

INFO:pypsa.io:Imported network elec.nc has buses, carriers, generators, lines, loads, shapes, transformers
INFO:__main__:Mapping all network lines onto a single 380kV layer
ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "C:\Users\M.Frank\Documents\GitHub\pypsa-eur\.snakemake\scripts\tmpld3wy5nn.simplify_network.py", line 542, in <module>
    n, trafo_map = simplify_network_to_380(n)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M.Frank\Documents\GitHub\pypsa-eur\.snakemake\scripts\tmpld3wy5nn.simplify_network.py", line 134, in simplify_network_to_380
    n.lines["num_parallel"] = n.lines.eval("s_nom / (sqrt(3) * v_nom * i_nom)")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M.Frank\.conda\envs\pypsa-eur\Lib\site-packages\pandas\core\frame.py", line 4949, in eval
    return _eval(expr, inplace=inplace, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M.Frank\.conda\envs\pypsa-eur\Lib\site-packages\pandas\core\computation\eval.py", line 357, in eval
    ret = eng_inst.evaluate()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M.Frank\.conda\envs\pypsa-eur\Lib\site-packages\pandas\core\computation\engines.py", line 81, in evaluate
    res = self._evaluate()
          ^^^^^^^^^^^^^^^^
  File "C:\Users\M.Frank\.conda\envs\pypsa-eur\Lib\site-packages\pandas\core\computation\engines.py", line 121, in _evaluate
    return ne.evaluate(s, local_dict=scope)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M.Frank\.conda\envs\pypsa-eur\Lib\site-packages\numexpr\necompiler.py", line 977, in evaluate
    raise e
  File "C:\Users\M.Frank\.conda\envs\pypsa-eur\Lib\site-packages\numexpr\necompiler.py", line 874, in validate
    _names_cache[expr_key] = getExprNames(ex, context, sanitize=sanitize)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M.Frank\.conda\envs\pypsa-eur\Lib\site-packages\numexpr\necompiler.py", line 723, in getExprNames
    ex = stringToExpression(text, {}, context, sanitize)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M.Frank\.conda\envs\pypsa-eur\Lib\site-packages\numexpr\necompiler.py", line 283, in stringToExpression
    raise ValueError(f'Expression {s} has forbidden control characters.')
ValueError: Expression (s_nom) / (((sqrt(np.float64(3.0))) * (v_nom)) * (i_nom)) has forbidden control characters.
RuleException:
CalledProcessError in file C:\Users\M.Frank\Documents\GitHub\pypsa-eur\rules/build_electricity.smk, line 494:
Command 'C:/Users/M.Frank/.conda/envs/pypsa-eur/python.exe "C:\Users\M.Frank\Documents\GitHub\pypsa-eur\.snakemake\scripts\tmpld3wy5nn.simplify_network.py"' return
ed non-zero exit status 1.
[Wed Jul 31 07:35:34 2024]
Error in rule simplify_network:
    jobid: 4
    input: resources/test/networks/elec.nc, resources/test/costs_2030.csv, resources/test/regions_onshore.geojson, resources/test/regions_offshore.geojson
    output: resources/test/networks/elec_s.nc, resources/test/regions_onshore_elec_s.geojson, resources/test/regions_offshore_elec_s.geojson, resources/test/busmap
_elec_s.csv
    log: logs/test/simplify_network/elec_s.log (check log file(s) for error details)
    conda-env: C:\Users\M.Frank\Documents\GitHub\pypsa-eur\.snakemake\conda\c790fd0743ac78fd314cfefc3d4521ad_

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake\log\2024-07-31T072630.993993.snakemake.log
WorkflowError:
At least one job did not complete successfully.

## Installed packages
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
amply                     0.1.6              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argparse-dataclass        2.0.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
atlite                    0.2.13             pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.7.22              h8c86ca4_10    conda-forge
aws-c-cal                 0.7.1                hea5f451_1    conda-forge
aws-c-common              0.9.23               h2466b09_0    conda-forge
aws-c-compression         0.2.18               hea5f451_7    conda-forge
aws-c-event-stream        0.4.2               h4b8288a_15    conda-forge
aws-c-http                0.8.2                h269d64e_6    conda-forge
aws-c-io                  0.14.10              hfca834b_1    conda-forge
aws-c-mqtt                0.10.4               h519d897_8    conda-forge
aws-c-s3                  0.6.0                hb746b11_2    conda-forge
aws-c-sdkutils            0.1.16               hea5f451_3    conda-forge
aws-checksums             0.1.18               hea5f451_7    conda-forge
aws-crt-cpp               0.27.3               h8c89294_2    conda-forge
aws-sdk-cpp               1.11.329             he0aa860_9    conda-forge
azure-core-cpp            1.12.0               haf5610f_0    conda-forge
azure-identity-cpp        1.8.0                h8578521_1    conda-forge
azure-storage-blobs-cpp   12.11.0              h39eb5e7_1    conda-forge
azure-storage-common-cpp  12.6.0               h8578521_1    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
blosc                     1.21.6               h85f69ea_0    conda-forge
bokeh                     3.5.0              pyhd8ed1ab_0    conda-forge
bottleneck                1.4.0           py311h0a17f05_1    conda-forge
branca                    0.7.2              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0           py311h12c1d0e_1    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
c-ares                    1.32.2               h2466b09_0    conda-forge
c-blosc2                  2.15.0               hb461149_1    conda-forge
ca-certificates           2024.7.4             h56e8100_0    conda-forge
cads-api-client           1.1.0              pyhd8ed1ab_0    conda-forge
cairo                     1.18.0               h91e5215_2    conda-forge
cartopy                   0.23.0          py311hcf9f919_1    conda-forge
cdsapi                    0.7.0              pyhd8ed1ab_0    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py311ha68e1ae_0    conda-forge
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
cfitsio                   4.4.1                hc2ea260_0    conda-forge
cftime                    1.6.4           py311h0a17f05_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda-inject              1.3.2              pyhd8ed1ab_0    conda-forge
configargparse            1.7                pyhd8ed1ab_0    conda-forge
connection_pool           0.0.3              pyhd3deb0d_0    conda-forge
contourpy                 1.2.1           py311h005e61a_0    conda-forge
country_converter         1.2                pyhd8ed1ab_0    conda-forge
cppad                     20240000.5           he0c23c2_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.3          py311ha68e1ae_0    conda-forge
dask                      2024.7.0           pyhd8ed1ab_0    conda-forge
dask-core                 2024.7.0           pyhd8ed1ab_0    conda-forge
dask-expr                 1.1.7              pyhd8ed1ab_0    conda-forge
datrie                    0.8.2           py311ha68e1ae_7    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
deprecation               2.1.0              pyh9f0ad1d_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
distlib                   0.3.8              pyhd8ed1ab_0    conda-forge
distributed               2024.7.0           pyhd8ed1ab_0    conda-forge
docutils                  0.21.2             pyhd8ed1ab_0    conda-forge
dpath                     2.2.0              pyha770c72_0    conda-forge
entsoe-py                 0.6.8              pyhd8ed1ab_0    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h63175ca_0    conda-forge
filelock                  3.15.4             pyhd8ed1ab_0    conda-forge
fiona                     1.9.6           py311hee68897_3    conda-forge
fmt                       10.2.1               h181d51b_0    conda-forge
folium                    0.17.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1          py311he736701_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freexl                    2.0.0                h8276f4a_0    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
fsspec                    2024.6.1           pyhff2d567_0    conda-forge
gdal                      3.9.1           py311h2711c7e_7    conda-forge
geographiclib             2.0                pyhd8ed1ab_0    conda-forge
geojson-rewind            1.1.0              pyhd8ed1ab_0    conda-forge
geopandas                 1.0.1              pyhd8ed1ab_0    conda-forge
geopandas-base            1.0.1              pyha770c72_0    conda-forge
geopy                     2.4.1              pyhd8ed1ab_1    conda-forge
geos                      3.12.2               h5a68840_0    conda-forge
geotiff                   1.7.3                hd7df778_1    conda-forge
getopt-win32              0.1                  hcfcfb64_1    conda-forge
gitdb                     4.0.11             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.43             pyhd8ed1ab_0    conda-forge
glib                      2.80.3               h7025463_1    conda-forge
glib-tools                2.80.3               h4394cf3_1    conda-forge
glpk                      5.0                  h8ffe710_0    conda-forge
graphite2                 1.3.13            h63175ca_1003    conda-forge
graphviz                  11.0.0               h09e431a_0    conda-forge
gst-plugins-base          1.24.5               hb0a98b8_0    conda-forge
gstreamer                 1.24.5               h5006eae_0    conda-forge
gts                       0.7.6                h6b5321d_4    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
harfbuzz                  9.0.0                h81778c3_0    conda-forge
hdf4                      4.2.15               h5557f11_7    conda-forge
hdf5                      1.14.3          nompi_h2b43c12_105    conda-forge
highspy                   1.7.2                    pypi_0    pypi
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
humanfriendly             10.0            py311h1ea47a8_5    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
identify                  2.6.0              pyhd8ed1ab_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
immutables                0.20            py311ha68e1ae_1    conda-forge
importlib-metadata        8.0.0              pyha770c72_0    conda-forge
importlib_metadata        8.0.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2023.2.0         h57928b3_50497    conda-forge
ipopt                     3.14.16              ha3daec3_4    conda-forge
ipython                   8.26.0             pyh7428d3b_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py311h1ea47a8_0    conda-forge
kealib                    1.5.3                h6c43f9b_1    conda-forge
kiwisolver                1.4.5           py311h005e61a_1    conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20240116.2      cxx17_he0c23c2_1    conda-forge
libaec                    1.1.3                h63175ca_0    conda-forge
libarchive                3.7.4                haf234dc_0    conda-forge
libarrow                  16.1.0          h11e6a32_14_cpu    conda-forge
libarrow-acero            16.1.0          he0c23c2_14_cpu    conda-forge
libarrow-dataset          16.1.0          he0c23c2_14_cpu    conda-forge
libarrow-substrait        16.1.0          h1f0e801_14_cpu    conda-forge
libblas                   3.9.0              20_win64_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              20_win64_mkl    conda-forge
libclang13                18.1.8          default_ha5278ca_0    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   8.8.0                hd5e4a3a_1    conda-forge
libdeflate                1.20                 hcfcfb64_0    conda-forge
libevent                  2.1.12               h3671451_1    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libgd                     2.3.3                h312136b_9    conda-forge
libgdal                   3.9.1                h57928b3_7    conda-forge
libgdal-core              3.9.1                h7e31c53_7    conda-forge
libgdal-fits              3.9.1                h0a0b71e_7    conda-forge
libgdal-grib              3.9.1                hd2a089b_7    conda-forge
libgdal-hdf4              3.9.1                h430f241_7    conda-forge
libgdal-hdf5              3.9.1                had131a1_7    conda-forge
libgdal-jp2openjpeg       3.9.1                hed4c6cb_7    conda-forge
libgdal-kea               3.9.1                h95b1a77_7    conda-forge
libgdal-netcdf            3.9.1                h55e78d3_7    conda-forge
libgdal-pdf               3.9.1                h261eb30_7    conda-forge
libgdal-pg                3.9.1                ha693a0f_7    conda-forge
libgdal-postgisraster     3.9.1                ha693a0f_7    conda-forge
libgdal-tiledb            3.9.1                h0c63b6b_7    conda-forge
libgdal-xls               3.9.1                hd0e23a6_7    conda-forge
libglib                   2.80.3               h7025463_1    conda-forge
libgoogle-cloud           2.26.0               h5e7cea3_0    conda-forge
libgoogle-cloud-storage   2.26.0               he5eb982_0    conda-forge
libgrpc                   1.62.2               h5273850_0    conda-forge
libhwloc                  2.11.1          default_h8125262_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_2    conda-forge
libintl-devel             0.22.5               h5728263_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
libkml                    1.3.0             h538826c_1020    conda-forge
liblapack                 3.9.0              20_win64_mkl    conda-forge
libnetcdf                 4.9.2           nompi_h92078aa_114    conda-forge
libogg                    1.3.5                h2466b09_0    conda-forge
libparquet                16.1.0          h178134c_14_cpu    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libpq                     16.3                 hab9416b_0    conda-forge
libprotobuf               4.25.3               h503648d_0    conda-forge
libre2-11                 2023.09.01           hf8d8778_2    conda-forge
librttopo                 1.1.0               h6c42fcb_16    conda-forge
libspatialite             5.1.0                hcb35769_8    conda-forge
libsqlite                 3.46.0               h2466b09_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libthrift                 0.19.0               ha2b3283_1    conda-forge
libtiff                   4.6.0                hddb2be6_3    conda-forge
libutf8proc               2.8.0                h82a8f57_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.4.0                h2466b09_0    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libxcb                    1.16                 hcd874cb_0    conda-forge
libxml2                   2.12.7               h0f24e4e_4    conda-forge
libxslt                   1.1.39               h3df6e99_0    conda-forge
libzip                    1.10.1               h1d365fa_3    conda-forge
libzlib                   1.3.1                h2466b09_1    conda-forge
linopy                    0.3.13             pyhd8ed1ab_0    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      5.2.2           py311h12967d8_0    conda-forge
lz4                       4.3.3           py311haddf500_0    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              hcfcfb64_1001    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.6.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py311ha68e1ae_0    conda-forge
matplotlib                3.9.1           py311h1ea47a8_0    conda-forge
matplotlib-base           3.9.1           py311h8f1b1e4_0    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
memory_profiler           0.61.0             pyhd8ed1ab_0    conda-forge
metis                     5.1.0             h63175ca_1007    conda-forge
minizip                   4.0.6                hb638d1e_0    conda-forge
mkl                       2023.2.0         h6a75c08_50497    conda-forge
mpfr                      4.2.1                h64bf75a_1    conda-forge
mpir                      3.0.0             he025d50_1002    conda-forge
msgpack-python            1.0.8           py311h3257749_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multiurl                  0.3.1              pyhd8ed1ab_0    conda-forge
mumps-seq                 5.7.2                h7c2359a_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
netcdf4                   1.7.1           nompi_py311hbdc12eb_101    conda-forge
networkx                  3.3                pyhd8ed1ab_1    conda-forge
nodeenv                   1.9.1              pyhd8ed1ab_0    conda-forge
numexpr                   2.10.0          mkl_py311hc8aec83_0    conda-forge
numpy                     2.0.0                    pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openjdk                   22.0.1               h57928b3_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openpyxl                  3.1.4           py311ha68e1ae_0    conda-forge
openssl                   3.3.1                h2466b09_2    conda-forge
orc                       2.0.1                h7e885a9_1    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py311hcf9f919_1    conda-forge
pango                     1.54.0               hbb871f6_1    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
partd                     1.4.2              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.44                h3d7b363_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.4.0          py311h5592be9_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.4               h63175ca_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
plac                      1.4.3              pyhd8ed1ab_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
polars                    1.1.0                    pypi_0    pypi
poppler                   24.07.0              h686f694_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                16.3                 h7f155c9_0    conda-forge
powerplantmatching        0.5.15             pyhd8ed1ab_0    conda-forge
pre-commit                3.7.1              pyha770c72_0    conda-forge
progressbar2              4.4.2              pyhd8ed1ab_0    conda-forge
proj                      9.4.1                hd9569ee_0    conda-forge
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
psutil                    6.0.0           py311he736701_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pulp                      2.8.0           py311h1ea47a8_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
pyarrow                   16.1.0          py311h06a5be4_4    conda-forge
pyarrow-core              16.1.0          py311hf9a78b3_4_cpu    conda-forge
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
pycountry                 24.6.1             pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyogrio                   0.9.0           py311h2494c99_0    conda-forge
pyomo                     6.6.1           py311h12c1d0e_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyproj                    3.6.1           py311h93f6e28_7    conda-forge
pypsa                     0.28.0             pyhd8ed1ab_0    conda-forge
pyqt                      5.15.9          py311h125bc19_5    conda-forge
pyqt5-sip                 12.12.2         py311h12c1d0e_5    conda-forge
pyreadline3               3.4.1           py311h1ea47a8_3    conda-forge
pyscipopt                 5.1.1           py311hda3d55a_0    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytables                  3.9.2           py311h1c470a5_3    conda-forge
pytest                    8.2.2              pyhd8ed1ab_0    conda-forge
python                    3.11.9          h631f459_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python-utils              3.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pywin32                   306             py311h12c1d0e_2    conda-forge
pyxlsb                    1.0.10             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py311ha68e1ae_1    conda-forge
qhull                     2020.2               hc790b64_5    conda-forge
qt-main                   5.15.8              h06adc49_23    conda-forge
rasterio                  1.3.10          py311hb019220_4    conda-forge
re2                       2023.09.01           hd3b24a8_2    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1                    pypi_0    pypi
reretry                   0.11.8             pyhd8ed1ab_0    conda-forge
rioxarray                 0.16.0             pyhd8ed1ab_0    conda-forge
rpds-py                   0.19.0          py311h533ab2d_0    conda-forge
scikit-learn              1.5.1           py311hdcb8d17_0    conda-forge
scip                      9.1.0                hb46ef20_0    conda-forge
scipy                     1.14.0          py311hd4686c6_1    conda-forge
seaborn                   0.13.2               hd8ed1ab_2    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_2    conda-forge
setuptools                71.0.1             pyhd8ed1ab_0    conda-forge
setuptools-scm            8.1.0              pyhd8ed1ab_0    conda-forge
setuptools_scm            8.1.0                hd8ed1ab_0    conda-forge
shapely                   2.0.5           py311hf837ac7_0    conda-forge
sip                       6.7.12          py311h12c1d0e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smart_open                7.0.4              pyhd8ed1ab_0    conda-forge
smmap                     5.0.0              pyhd8ed1ab_0    conda-forge
snakemake-executor-plugin-cluster-generic 1.0.9                    pypi_0    pypi
snakemake-executor-plugin-slurm 0.8.0                    pypi_0    pypi
snakemake-executor-plugin-slurm-jobstep 0.2.1                    pypi_0    pypi
snakemake-interface-common 1.17.2             pyhdfd78af_0    bioconda
snakemake-interface-executor-plugins 9.2.0              pyhdfd78af_0    bioconda
snakemake-interface-report-plugins 1.0.0              pyhdfd78af_0    bioconda
snakemake-interface-storage-plugins 3.2.3              pyhdfd78af_0    bioconda
snakemake-minimal         8.16.0             pyhdfd78af_0    bioconda
snakemake-storage-plugin-http 0.2.3                    pypi_0    pypi
snappy                    1.2.1                h23299a8_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
spdlog                    1.13.0               h64d2f7d_0    conda-forge
sqlite                    3.46.0               h2466b09_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.2          py311h0a17f05_0    conda-forge
stopit                    1.1.2                      py_0    conda-forge
symlink-exe-runtime       1.0                  hcfcfb64_0    conda-forge
tabula-py                 2.7.0           py311h1ea47a8_1    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tbb                       2021.12.0            hc790b64_3    conda-forge
tblib                     3.0.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
throttler                 1.2.2              pyhd8ed1ab_0    conda-forge
tiledb                    2.24.2               h297c385_2    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
toposort                  1.10               pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py311he736701_0    conda-forge
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
tsam                      2.3.1                    pypi_0    pypi
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
ukkonen                   1.0.1           py311h005e61a_4    conda-forge
unidecode                 1.3.8              pyhd8ed1ab_0    conda-forge
uriparser                 0.9.8                h5a68840_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
validators                0.33.0             pyhd8ed1ab_0    conda-forge
vc                        14.3                h8a93ad2_20    conda-forge
vc14_runtime              14.40.33810         ha82c5b3_20    conda-forge
virtualenv                20.26.3            pyhd8ed1ab_0    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.16.0          py311ha68e1ae_0    conda-forge
xarray                    2024.6.0           pyhd8ed1ab_1    conda-forge
xerces-c                  3.2.5                he0c23c2_1    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.1.1                hcd874cb_0    conda-forge
xorg-libsm                1.2.4                hcd874cb_0    conda-forge
xorg-libx11               1.8.9                h0076a8d_1    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_2    conda-forge
xorg-libxpm               3.5.17               hcd874cb_0    conda-forge
xorg-libxt                1.3.0                hcd874cb_1    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1003    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xyzservices               2024.6.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yte                       1.5.4              pyha770c72_0    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                h2466b09_1    conda-forge
zlib-ng                   2.2.1                he0c23c2_0    conda-forge
zstandard                 0.23.0          py311h53056dc_0    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge

# Thanks for any ideas!

**Comment by fneum** [comment]
For Windows, we recommend [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux). This looks like an OS-specific problem.

**Comment by fneum** [comment]
reopen if issue persists on Windows with WSL

**Comment by MichaelGeFr** [comment]
When using WSL the problem does not persist. Thank you!
