### ISSUE TITLE
Zenodo cutout data files name not in sync with config.

### ISSUE THREAD

**Issue by shithikanta** [PyPSA/pypsa-eur#1200]
## Checklist

- [ yes] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [ yes] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

The Cutout data file name in the configuration is not matching with the datasets available in the Zenodo repository. The following error is shown: 

## Error Message

![image](https://github.com/user-attachments/assets/9df89cad-3d3e-4684-a782-802afbd755bf)

**Comment by fneum** [comment]
Is `config/config.default (1).yaml" perhaps from a previous commit? We updated the files on zenodo recently. Maybe also delete `config/config.yaml` if it comes from a previous version.
