### ISSUE TITLE
Unnecessary code in solve_operations_network.py ?

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#121]
It seems a bit overheaded that the network assignment is done by loading the prepared (but not solved network) and then [overwrite extendable attributes extracted from the solved network](https://github.com/PyPSA/pypsa-eur/blob/52e4a1b285a16ebd487f599018b1b250368d7ade/scripts/solve_operations_network.py#L55). 

Why don't we go for something like this:
```python 
    n = pypsa.Network(snakemake.input.optimized)
    for c, attr in pypsa.descriptors.nominal_attrs.items():
        n.df(c)[attr] = n.df(c)[attr + '_opt']
        n.df(c)[attr + '_extendable'] = False
```
 which would lead to much less code. But I might overlook something...

**Comment by coroa** [comment]
Capacity optimized code is typically 3H while operations networks should be possible hourly!

**Comment by FabianHofmann** [comment]
yes, that is the difference! It definitely makes sense to keep the hourly time resolution for the operational case. I plan to test it for different networks, and raise an issue when I run into the same infeasibility. Thanks for clarifying
