### ISSUE TITLE
environment files several fails in packages

### ISSUE THREAD

**Issue by kiliamk** [PyPSA/pypsa-eur#125]
## Checklist

- I am cloned the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch 
- When creating any of the environments from either the environments.yaml or the environments.fixedversion.yaml both have problems installing certain packages. 

-environments.fixedversion.yaml troubles among these: 
   - openmp_impl = 4.5
   - geokit == 1.1.2
   - glaes == 1.1.2

## Describe the Bug  & ## Error Message

when creating the environment promts that Pip failed... 

## Other users also had the same trouble 5/Feb/2020

**Comment by FabianHofmann** [comment]
Hey @kiliamk, this is definitely not wanted, thanks for reporting. It might well be that the PR #116 fixes this. Could you try out this [environmemt](https://github.com/PyPSA/pypsa-eur/blob/nomopyomo/environment.yaml) file?

**Comment by kiliamk** [comment]
When I click in "environment" it brings me to: "404 This is not the web
page you are looking for"

Am Do., 6. Feb. 2020 um 12:17 Uhr schrieb FabianHofmann <
notifications@github.com>:

**Comment by FabianHofmann** [comment]
Yes the branch was deleted, since the PR is already merged. Can you try out with the current master again.

**Comment by kiliamk** [comment]
I undestand you mean to download the environment again as usual and
installing. I'll do so

Am Mo., 10. Feb. 2020 um 14:11 Uhr schrieb FabianHofmann <
notifications@github.com>:

**Comment by fneum** [comment]
@kiliamk I think we solved it together, right? No need to change anything in this repository (other than `environment.fixedversion.yaml` which will receive an update for the next release. If not, please feel free to re-open.
