### ISSUE TITLE
store config.yaml with (solved) networks for reproducibility

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#126]
copy approach from pypsa-eur-sec

**Comment by coroa** [comment]
Note that for reproducibility, I have also been a big fan of using [borgbackup](https://www.borgbackup.org/), on completed runs, by invoking `./borg-it <memorable-name>` in the top-level dir.

**Comment by fneum** [comment]
closed via https://github.com/PyPSA/pypsa-eur/pull/246
