### ISSUE TITLE
CO2 constraints silently change the carrier of stores

### ISSUE THREAD

**Issue by lindnemi** [PyPSA/pypsa-eur#1261]
In https://github.com/PyPSA/pypsa-eur/blob/b32816973fddf9cfaccd3a561e884fee96be0c71/scripts/solve_network.py#L333-L334,  https://github.com/PyPSA/pypsa-eur/blob/b32816973fddf9cfaccd3a561e884fee96be0c71/scripts/solve_network.py#L359-L360 and https://github.com/PyPSA/pypsa-eur/blob/b32816973fddf9cfaccd3a561e884fee96be0c71/scripts/solve_network.py#L1003-L1004.

The carrier of stores is changed to be equal to the bus_carrier. This should not happen and may cause confusion afterwards. In my case, the carrier was changed from `unsustainable solid biomass` to `solid biomass`.

**Comment by fneum** [comment]
closed via #1262
