### ISSUE TITLE
Missing dependency for rule prepare_links_p_nom

### ISSUE THREAD

**Issue by euronion** [PyPSA/pypsa-eur#129]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/environment.yaml). Update via `conda env update -f environment.yaml`.

## Describe the Bug

Running `snakemake prepare_links_p_nom` fails with the current `environment.yaml` due to missing dependencies (`lxml` or `html5lib`).

## Error Message

```
Traceback (most recent call last):
  File "/<dir>/pypsa-eur-v010/.snakemake/scripts/tmpafr1f61a.prepare_links_p_nom.py", line 50, in <module>
    links_p_nom = pd.read_html('https://en.wikipedia.org/wiki/List_of_HVDC_projects', header=0, match="SwePol")[0]
  File "/opt/conda/envs/dockerenv/lib/python3.7/site-packages/pandas/io/html.py", line 1105, in read_html
    displayed_only=displayed_only,
  File "/opt/conda/envs/dockerenv/lib/python3.7/site-packages/pandas/io/html.py", line 888, in _parse
    parser = _parser_dispatch(flav)
  File "/opt/conda/envs/dockerenv/lib/python3.7/site-packages/pandas/io/html.py", line 843, in _parser_dispatch
    raise ImportError("lxml not found, please install it")
```

## Background

* The file `data/links_p_nom.csv` is required for the workflow.
* By default, the file is distributed with the git repository (although it was later added to `.gitignore`), so the version distributed is not representing an up-to-date version from wikipedia.
* `pandas` requires either `lxml` or `beautifulsoup4` + `html5lib` to be installed to use `read_html` in `scripts/prepare_links_p_nom.py`. Dependencies `lxml` or `html5lib` are not included in the current `environment.yaml`.
* Until recently, this was not a problem, as the `config.defauly.yaml` was setup to not include the recreation of `data/links_p_nom.csv` into the workflow (`enable` -> `prepare_links_p_nom: false`). This changed in https://github.com/PyPSA/pypsa-eur/commit/5934f4f7a110ca4c745baaa30f90c6e667c7e04d .

## Possible fixes

* Include the required dependency `html5lib` into `environment.yaml` ( `lxml` is more complicated to install) and then change 
https://github.com/PyPSA/pypsa-eur/blob/8bed137ca53d9458f61420c51af6e05228cea3de/scripts/prepare_links_p_nom.py#L46

to 
```
links_p_nom = pd.read_html('https://en.wikipedia.org/wiki/List_of_HVDC_projects', header=0, match="SwePol", flavor="html5lib")[0]
```
as the selection mechanism in `pandas` does not seem to work properly (has been reported multiple times over the flow of time).

so the file is always recreated.
* Include the file into an upcoming version of the databundle and remove from git. Also set the default for recreating the file as `false` again.

**Comment by fneum** [comment]
Thanks for looking into this. I had `lxml` in a fresh environment installed. Download of new `data/links_p_nom.csv` was successful.
