### ISSUE TITLE
Pin vresutils version to 0.3.1

### ISSUE THREAD

**Issue by coroa** [PyPSA/pypsa-eur#137]
That pypsa-eur is refering to the git version of vresutils is blocking https://github.com/FRESNA/vresutils/pull/14#pullrequestreview-345963311

**Comment by fneum** [comment]
If I understand correctly, there should also be a new (minor) PyPSA-Eur release since https://github.com/PyPSA/pypsa-eur/releases/tag/v0.1.0 also refers to `vresutils@master`, right?

Should do this after PyPSA 0.17.0 release soon.

**Comment by fneum** [comment]
And sorry for the delay. The mention in FRESNA/vresutils#14 slipped through.

**Comment by coroa** [comment]
> If I understand correctly, there should also be a new (minor) PyPSA-Eur release since https://github.com/PyPSA/pypsa-eur/releases/tag/v0.1.0 also refers to `vresutils@master`, right?

Correct

**Comment by fneum** [comment]
This is pinned to `vresutils==0.3.1` in latest release https://github.com/PyPSA/pypsa-eur/tree/v0.2.0
