### ISSUE TITLE
Clarify usage of option "-call"

### ISSUE THREAD

**Issue by fhg-isi** [PyPSA/pypsa-eur#1385]
The option "-call" that is used for the tutorials might be misleading, as "call" could be interpretet as single word like in "call a function" and when searching for it in the snakemake documentaiton, it cannot be found. Also see

https://github.com/PyPSA/PyPSA/issues/1060

Current version of snakemake does not seem to require the --cores (-c) option any more and uses all cores by default:

https://github.com/snakemake/snakemake/issues/3167

=> I would prefer one of the following variants to avoid confusion by "black magic" command `snakemake -call` :

```
snakemake
snakemake --cores
snakemake --coresall
snakamake -c
```

**Comment by lkstrp** [comment]
While it still can be used, `-call` is indeed optional and not documented anymore. Thank you @fhg-isi !
