### ISSUE TITLE
missing CPLEX support since #116

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#139]
Switching to `pyomo=False` in #116 in the `solve_network` rule had an unintended side-effect, namely that using CPLEX is not supported anymore.

As there are existing users of PyPSA-Eur who use CPLEX, this should be addressed quickly by either

a) implementing CPLEX support for pypsa/pypsa#160 (@FabianHofmann is that difficult?) or
b) reintroducing the previous `pyomo=True` code in parallel to the `pyomo=False` code for the `solve_network` rule and make it a configurable option to switch between the two.

Sorry, that I didn''t notice earlier that this could be a problem!

@nworbmot  @FabianHofmann

**Comment by FabianHofmann** [comment]
@fneum very true, I did't have CPLEX in mind either! I would definitely go for the first option. I'll make a PR in pypsa for the CPLEX solver asap

**Comment by fneum** [comment]
fixed in https://github.com/PyPSA/PyPSA/pull/164 with approach a)
