### ISSUE TITLE
Missing colors of various technologies/carriers

### ISSUE THREAD

**Issue by p-glaum** [PyPSA/pypsa-eur#1396]
## Describe the Bug
I noticed while plotting that we have various technologies without a tech_color defined in the config. For plotting purposes, we should have for every technology/carrier added to the network one color in the default.config.yaml. Some examples for technologies without color are:
```
['', 'none', 'rural solar thermal', 'rural water tanks', 'urban decentral heat', 'urban decentral solar thermal', 'urban decentral water tanks', 'rural air heat pump', 'biomass to liquid CC', 'rural biomass boiler', 'urban decentral air heat pump', 'urban decentral water tanks discharger', 'rural resistive heater', 'urban decentral water tanks charger', 'urban decentral biomass boiler', 'urban decentral resistive heater', 'urban decentral gas boiler', 'rural gas boiler', 'rural ground heat pump', 'rural water tanks charger', 'rural water tanks discharger']
```

**Comment by amos-schledorn** [comment]
@p-glaum I haven't actually touched those but happy to add colours. We seem to have plotting colors for related technologies (for example `residential rural gas boiler` and `services rural gas boiler` rather than `rural gas boiler`). We could copy the colours for those technologies to match the ones you need?

**Comment by p-glaum** [comment]
yes, we could do that. But I was also thinking that we should not overload the config. Maybe it is better to define technology groups that share the same color, like heat pumps.
