### ISSUE TITLE
Large RHS values when solving with gurobi

### ISSUE THREAD

**Issue by ClaraBuettner** [PyPSA/pypsa-eur#1406]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch (last commit https://github.com/PyPSA/pypsa-eur/commit/464c4cff675196a31dc88d802e612ca2e21771b9)
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). I use the linux-pinned.yaml file to create my environment.

## Describe the Bug

When I try to solve a network with gurobi I run into numerical problems due to large rhs (1e+100), and the problem can not be solved.
The large rhs values are caused by PyPSA's new constraints Generator-e-sum-max. I did not define a limit, so the default value (inf) is used. When I drop these constraints, the rhs is way lower, and the problem can be solved.
I don't know if the problem is caused by pypsa-eur, PyPSA, linopy or gurobi. I posted the issue in this repository because I found the problem here. 
I can reproduce the problem in a small PyPSA-example (version 0.31.1) when I try to solve it with gurobi: 
```
import pypsa
n = pypsa.examples.ac_dc_meshed(from_master=True)
n.optimize(solver_name="gurobi")
```
Although the problem was solved, the maximum rhs is huge (1e+100). When I run the same problem with the default solver HiGHS, the rhs are much lower.

**Comment by fneum** [comment]
Thanks for flagging! It's always good to try out new features!

I think it would make sense to skip the e-sum-max constraints where no limit is set. @cpschau, could you take a look?

**Comment by cpschau** [comment]
> Thanks for flagging! It's always good to try out new features!
> 
> I think it would make sense to skip the e-sum-max constraints where no limit is set. @cpschau, could you take a look?

Sure! @lkstrp also recently flagged a problem with the constraint in combination using CPLEX.

**Comment by lkstrp** [comment]
Yeah, same issue. CPLEX couldn't handle infs and just threw an error.
PyPSA `0.31.0` introduced the problem, and the current master of `linopy` already fixes this by dropping all inf constraints. No need to add any e-sum-max specific changes.

@ClaraBuettner 
So you could fix the error by installing `linopy` from git via: 
```
pip install git+https://github.com/PyPSA/linopy.git
```
Otherwise wait for a new linopy release. I can push one soon.
