### ISSUE TITLE
Create conda environment, results in “Found conflicts!”

### ISSUE THREAD

**Issue by JanFrederickUnnewehr** [PyPSA/pypsa-eur#142]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/environment.yaml). Update via `conda env update -f environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

The creation of the environment currently leads to compatibility errors between packages.
Recently you added the "defaults" channel to the `environment.yaml` file. Getting some packages from different channels can lead to the error listed below. By commenting out the line 3 `- defaults` in the `.yaml` file the environment is created successfully.

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
(base) freddy@intgrid-pc-08:~/Dokumente/pypsa-eur_50/pypsa-eur$ conda env create -f environment.yaml
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```

**Comment by fneum** [comment]
Was a bit of a gamble last time, wasn't it @FabianHofmann #116?

**Comment by FabianHofmann** [comment]
mhh, that's nasty. Normally specifying the defaults channel should end up in a stable configuration. But if the opposite is the case...

**Comment by JanFrederickUnnewehr** [comment]
I was also wondering and tested the behavior only on Linux. This issue https://github.com/bioconda/bioconda-recipes/issues/17186 describes a similar behavior.

**Comment by fneum** [comment]
Any more of these errors recently? Trying `mamba` is also a good idea if this occurs. I will close this issue as the `environment.yaml` has changed and tests are passing. @JanFrederickUnnewehr just reopen if you think this issue persists.

**Comment by zoltanmaric** [comment]
I recently encountered this issue on `osx-arm64`. I resolved it by moving the `pypsa` into the `pip` dependencies. No idea why that works.

**Comment by zoltanmaric** [comment]
> I recently encountered this issue on `osx-arm64`. I resolved it by moving `pypsa` into the `pip` dependencies. No idea why that works.

In my case this happened because `pyomo` and `tabula-py` were not available as conda packages for `osx-arm64`, so I moved them to the `pip` dependencies in the environment file. I resolved the issue by also moving `pypsa` to the `pip` dependencies.
