### ISSUE TITLE
Snakemake latest version leads to WorkflowError

### ISSUE THREAD

**Issue by tgilon** [PyPSA/pypsa-eur#1439]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch.
- [x] I am running on an **pinned** up-to-date [`pypsa-eur` pinned](https://github.com/PyPSA/pypsa-eur/blob/master/envs/linux-pinned.yaml).

## Describe the Bug

Using the current [`envs/linux-pinned.yaml`](https://github.com/PyPSA/pypsa-eur/commit/75623efff4d20327eabdc194e448b7e165ed12ca), the current `snakemake` version is `snakemake-minimal=8.25.3`. This version throws a `WorkflowError`.

## Error Message

```
WorkflowError:
Error running conda info. Is conda installed and accessible? Error: Command 'conda info --json' returned non-zero exit status 127.
```

## Solution

The version `snakemake-minimal=8.24.1` solves the problem. It might be a good idea to temporarily limit the version of Snakemake.

**Comment by lkstrp** [comment]
Thank you @tgilon !
