### ISSUE TITLE
In Snakemake 5.11 the --coures option is mandatory

### ISSUE THREAD

**Issue by JanFrederickUnnewehr** [PyPSA/pypsa-eur#146]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/environment.yaml). Update via `conda env update -f environment.yaml`.

## Describe the Bug

Running a snakemake with version 5.11.0 and higher on an existing workflows from pypsa-eur fails immediately with:
Error: you need to specify the maximum number of CPU cores to be used at the same time

In snakelike 5.11 they change --coures option to a mandatory option.
https://snakemake.readthedocs.io/en/stable/project_info/history.html

The behavior is also reported her:
https://github.com/snakemake/snakemake/issues/283

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
Error: you need to specify the maximum number of CPU cores to be used at the same time
```

**Comment by fneum** [comment]
Yes, I didn't like the change either, but fixed the documentation and CI in https://github.com/PyPSA/pypsa-eur/commit/0c6c23478b605de88b75842b0ab885db144934d5 yesterday. You can also define `--cores` in previous snakemake version.
