### ISSUE TITLE
gurobi solver & anaconda gurobi can lead to a version conflict

### ISSUE THREAD

**Issue by JanFrederickUnnewehr** [PyPSA/pypsa-eur#148]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/environment.yaml). Update via `conda env update -f environment.yaml`.

## Describe the Bug

The usage of conda gurobi ([link](https://github.com/PyPSA/pypsa-eur/commit/e6a1da299661451748e78d0f6edc878e3fc97154)) can lead to a version conflict if the Gurobi Solver has been installed on the computer for a long time ago.

Conda gurobi can only work together with Gurobi Solver if they both have the same version (9.x or 8.x).

https://www.gurobi.com/documentation/9.0/quickstart_linux/ins_the_anaconda_python_di.html

**Comment by fneum** [comment]
Yes, true. It's however hard to automatically handle this in the `environment.yaml`. Options I can think of right now:

- remove `gurobi::gurobi` from `environment.yaml` and add detailed documentation on installing solvers (also newly supported `cplex` for `pyomo=False` requires a conda/pip package) including alignment of versions (how to check gurobi version and install corresponding conda package.
- ask everyone to use up to date gurobi version.

**Comment by JanFrederickUnnewehr** [comment]
Yes, I agree. I think a short comment in the documentation should be enough here. The error will surely only appear with very few users.
