### ISSUE TITLE
simplify script aggregates Corsica to Italy

### ISSUE THREAD

**Issue by martacki** [PyPSA/pypsa-eur#152]
full resolution includes one bus for corsica (bus "2306"), that, when simplifying, gets aggregated to Italy "Festland" (bus "2343") which we do not want to happen.

The bug is in the script "simplify_network.py", ie. happens in the step when going from elec.nc to elec_s.nc. The function where the bug happens is "simplify_links", where chains of links (HVDC lines) are aggregated to one representative link (HVDC line).

**Comment by fneum** [comment]
So the solution would be to not aggregate links that cross countries? E.g.

```
IT ---link--- FR ---link--- IT
```

**Comment by eb5194** [comment]
I was thinking how to fix it as well, and that would fix it only by accident. We wouldn't want Corsica to be aggregated to France "Festland" as well if the link was from Corsica to France... right? Is that because it's an island, or an own synchronous zone? Or both?

BTW, I think that there are more than this case were HVDC links are aggregated across country borders. simplify_links doesn't take countries & synchronous zones into account at all. Maybe that has to be added?

**Comment by euronion** [comment]
Is it an option to specifically state the cases, where the simplification should not happen, e.g. an exception list?
While it might not be the most elegant solution, it is usually easier to understand and guaranteed to not accidentally apply to buses where it should not apply to.

**Comment by eb5194** [comment]
it would be definitely super easy to exclude this particular aggregation by removing the corresponding entry from the simplify_links_map. but doesn't fix all the (potential other cases where we aggregate across country/synch-zone bounderies. I could check how many cases we're talking about here?...

**Comment by nworbmot** [comment]
I don't know if this helps, but I noticed looking at the bus region shapes that Corsica is always aggregated to mainland France (even for 256 clusters), whereas Sardinia always remains its own synchronous area and a separate region. Perhaps something is going wrong with the country shapes?

**Comment by fneum** [comment]
@martacki do you have an overview if this is still the case or the issue can be closed?

**Comment by p-glaum** [comment]
@martacki is this issue solved?

**Comment by martacki** [comment]
@p-glaum no... but the work-around is rather ugly, and would add +1 node to the lowest resolution making it 38 nodes. we should discuss if we really want that

**Comment by fneum** [comment]
Closed via #1215
