### ISSUE TITLE
Documentation as CC-BY-4.0

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#155]
Differentiate license by content. Keep code as GPLv3, documentation as CC-BY-4.0 (to facilitate re-use of pictures etc., as done in upcoming `atlite` version)

**Comment by euronion** [comment]
We use(d) the FSFE REUSE tool to check for compliance.
It is of great help to make sure all files are compliant.

They also have a GitHub action/travis+docker image available to run the REUSE tool as a CI step. I guess incoporating this afterwards makes sense.

Documentation: https://reuse.software/dev/

**Comment by fneum** [comment]
closed with #160
