### ISSUE TITLE
Introduce atlite v0.2

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#162]
As we are approaching the release of atlite v0.2, there is some direct implications for pypsa-eur-(sec)

# Environment
pin the environment to the current version the master branched in [atlite v0.0.3](https://github.com/PyPSA/atlite/tree/v0.0.3). This should also happen in pypsa-eur-sec. @fneum could you take over this part? 

# Renewable profiles
As pointed out in https://github.com/PyPSA/atlite/issues/81#issuecomment-639190595 there might be some minimal invasive ways to account for the new convention in atlite which we should try out. @euronion you already tried those? At the moment I am not sure how this convention change, might inflict with the new version of glaes #156 ? We should tackle this in one strike

**Comment by euronion** [comment]
> # Renewable profiles
> 
> As pointed out in [PyPSA/atlite#81 (comment)](https://github.com/PyPSA/atlite/issues/81#issuecomment-639190595) there might be some minimal invasive ways to account for the new convention in atlite which we should try out. @euronion you already tried those? At the moment I am not sure how this convention change, might inflict with the new version of glaes #156 ? We should tackle this in one strike

Tried it before. Didn't work. The changes are more extensive than that. I already created the draft PR with a modified script which I deem more understandable (as it explicitly exposes the meta data in each step). And it also works AFAICT. I already have the scripts prepared for comparing the workflow script results of the old atlite version with the new atlite version.
I'll post the results as soon as I have tested everything on my todo in the `atlite` repository.

**Comment by euronion** [comment]
After discussing with @fneum we'll create a tag for `atlite` with the most recent `master` branch as soon as we are ready to merge the new version.

I'll then pin the `atlite` version with a separate PR for this version of PyPSA-EUR.
For the new version of PyPSA-EUR we will then also use the new version of `atlite` (hopefully).

Is this approach aok?

**Comment by fneum** [comment]
Just checking if I understood correctly:

- Make a release `v0.0.3` for atlite before merging `v0.2`.
- In PyPSA-Eur `master` environment pin `atlite=0.0.3` (PR by @euronion).
- Then, prepare and merge PR for transition from `atlite=0.0.3` to `atlite=0.2`.
- Make a release `v0.2` for PyPSA-Eur

Is that the plan? Sounds good.

**Comment by fneum** [comment]
PyPSA-Eur-Sec doesn't have it's own `environment.yaml` but takes the regular PyPSA-Eur environment.

If we were using the `git submodule` proposed in
https://github.com/PyPSA/pypsa-eur-sec/pull/59
we could manage the `atlite` transition also in PyPSA-Eur-Sec,
but it also somehow comes inherently with the current setup when we pin `atlite=0.0.3`.

AFAIK, there's only some changes necessary regarding the heat demand in PyPSA-Eur-Sec.

**Comment by coroa** [comment]
Atlite 0.0.3 was just released on PyPI and conda. Please add a version pin to master.

**Comment by fneum** [comment]
See #162. Will merge once tests have passed.
PyPSA-Eur `0.1.0` retrieves `atlite` from `conda-forge` without any version constraints.

**Comment by coroa** [comment]
>  PyPSA-Eur `0.1.0` retrieves `atlite` from `conda-forge` without any version constraints. So no new release necessary for now.

Well, this implies, we need a PyPSA-Eur release 0.1.1 with the version constraint before releasing atlite 0.2 to conda-forge.

**Comment by euronion** [comment]
Don't we have the `environment.fixedversions.yaml` exactly for this purpose? To provide the exact package versions used for a release? While the `environment.yaml` allows one to always utilise to most recent upstream changes?

**Comment by fneum** [comment]
Just now released PyPSA-Eur `v0.2.0`. Preferred this over a minor release `v0.1.1` since there were already quite substantial changes since `v0.1.0`.

**Comment by coroa** [comment]
> Don't we have the `environment.fixedversions.yaml` exactly for this purpose? To provide the exact package versions used for a release? While the `environment.yaml` allows one to always utilise to most recent upstream changes?
`environment.yaml` should list known version incompabilities as best as it can, so that for the trusting/naive user it just works.
 
If we are able to anticipate them, as we can now that's ideal: We do know that `v0.1.0` will NOT work with atlite `v0.2`. It's good practice to reflect that in environment.yaml.

`fixedversions` is meant to be a last resort that we can point to if the computed environment fails to work.
