### ISSUE TITLE
Use cost data from PyPSA/technology-data

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#179]
https://github.com/PyPSA/technology-data

**Comment by FabianHofmann** [comment]
Note on getting the data: 

When not wanting to download the whole tech-data repo, we can just download the csv file. Using curl this would go like this 

```
curl https://raw.githubusercontent.com/PyPSA/technology-data/v0.1.0/outputs/costs_2030.csv -o ./data/costs.csv
```

2030 could then be replaced by `config['cost']['year']`. The tag would be hard-coded (there might be a nicer way, but atm I don't know which).

**Comment by fneum** [comment]
That's what we do with the powerplants.csv, right? We could also have the `technology-data` tag in the `config.yaml`:

```py
config['cost']['version']
```

**Comment by FabianHofmann** [comment]
exactly, yes we could set the version in the config. 

As we currently still support windows machines, we probably should go for another .py script (e.g. `retrieve_cost_data.py`), even though a small bash snippet would be more elegant...
