### ISSUE TITLE
Power plant decommissioning years

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#185]
As pointed out by @nworbmot, we have to be careful with artificial decommissioning years. These are set in the script `build_powerplants.py` when calling the function `fill_missing_decommyears()`. It is based on a lot of heuristics. Probably, we should remove this call, and hope for better (and real) decommissioning data in the next `ppm` version.

**Comment by martavp** [comment]
On a related note, this database could be useful to update the coal early decommissioning

https://beyond-coal.eu/coal-exit-tracker/?type=maps&layer=1

**Comment by fneum** [comment]
@FabianHofmann a lot has been done on this recently, right? Would you say this issue can be closed? xref #363 #353

**Comment by FabianHofmann** [comment]
yes :)
