### ISSUE TITLE
Missing renewable profiles

### ISSUE THREAD

**Issue by ulicious** [PyPSA/pypsa-eur#187]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/environment.yaml). Update via `conda env update -f environment.yaml`.

## Describe the Bug

I have added cutouts covering several years and adjusted the config file regarding this period:

`snapshots:
  start: "2010-01-01"
  end: "2011-12-31"
  closed: 'left' # end is not inclusive`

Running the pypsa-eur with snakemake results/networks/elec_s_10_ec_lcopt_Co2L-1H.nc --cores all, I do get an warning that not all renewable profiles exist for the period. This message occurs while running the add_electricity.py step (I guess its from the attach_wind_and_solar method)

I checked the snapshots and the snapshots for the 12th month for both years are missing. If I understood the documentation on the config file right, only the 2011-12-31 should be missing but it seems that the build_renewable_profile script messes up the months of both years.

When running the pypsa-eur with:

`snapshots:
  start: "2010-01-01"
  end: "2012-01-01"
  closed: 'left'

no warning occured and the snapshots showed that renewable profiles where set without the default value for the whole period from 2010-01-01 to 2011-12-31

My first guess was the build_renewable_profile.py, where the profiles are created, and the snapshots where indeed missing already here. I did not further inspect the issue because I solved the problem by changing the end to 2012-01-01 in the config file.

## Error Message

Warning message for missing profiles:

`WARNING:pypsa.io:Snapshots DatetimeIndex(['2010-12-01 00:00:00', '2010-12-01 01:00:00',
               '2010-12-01 02:00:00', '2010-12-01 03:00:00',
               '2010-12-01 04:00:00', '2010-12-01 05:00:00',
               '2010-12-01 06:00:00', '2010-12-01 07:00:00',
               '2010-12-01 08:00:00', '2010-12-01 09:00:00',
               ...
               '2011-12-30 14:00:00', '2011-12-30 15:00:00',
               '2011-12-30 16:00:00', '2011-12-30 17:00:00',
               '2011-12-30 18:00:00', '2011-12-30 19:00:00',
               '2011-12-30 20:00:00', '2011-12-30 21:00:00',
               '2011-12-30 22:00:00', '2011-12-30 23:00:00'],
              dtype='datetime64[ns]', length=1464, freq=None) are missing from p_max_pu of Generator. Filling with default value '1.0'`

**Comment by fneum** [comment]
Hi @ulicious,

thanks for making us aware of this issue.

To my knowledge we had never tested the workflow for time series that spanned more than one year, but not exactly two/three/four years.

The origin of the error is here:

https://github.com/PyPSA/pypsa-eur/blob/09885518966ecf2b5422d5e4e0360b387107ba33/scripts/build_renewable_profiles.py#L284-L285

which for 

```yaml
snapshots:
    start="2010-01-01",
    end="2011-12-31",
    closed='left'
```

returns

```
{'years': slice(2010, 2011, None), 'months': slice(1, 11, None)}
```

This dictionary is needed owing to the way the atlite cutouts are stored in monthly chunks. AFAIK this will change in an upcoming `atlite` version #162, which is why I wouldn't tackle this bug right now.

Do you need this feature, or are you fine running exactly two years with

```yaml
snapshots:
    start="2010-01-01",
    end="2012-01-01",
    closed='left'
```

?
