### ISSUE TITLE
solve_network: add integral transmission expansion for impedance update and post-facto discretization

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#19]
Add heuristics to approximate integer transmission line expansion.

**Comment by coroa** [comment]
So you will integrate PSA.jl into the PyPSA-Eur workflow?

**Comment by fneum** [comment]
Decided the current impedance update is sufficient since especially in PyPSA-Eur we move everything to 380 kV which is already a big approximation. Convince me if you think otherwise.
