### ISSUE TITLE
Error due to package dependencies for pypsa-eur-sec

### ISSUE THREAD

**Issue by lukasnacken** [PyPSA/pypsa-eur#215]
I recently installed pypsa-eur and pypsa-eur-sec. The workflow of the latter reads xlsx files. The newest version of the package xlrd removed support for anything other than .xls files (https://xlrd.readthedocs.io/en/latest/changes.html). Thus, i got the following error:

> ValueError: Your version of xlrd is 2.0.1. In xlrd >= 2.0, only the xls format is supported. Install openpyxl instead.

The simplest fix for this issue is probably to add openpyxl to the list of dependencies of the environment files.

**Comment by fneum** [comment]
Great, can you verify that this does indeed solve the issue and prepare a PR for ´envs/environment.yaml´?

**Comment by lukasnacken** [comment]
Yes, installing openpyxl did solve the issue for me.
