### ISSUE TITLE
Operations-Only optimization still expands links

### ISSUE THREAD

**Issue by tinloaf** [PyPSA/pypsa-eur#217]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

The function [set_parameters_from_optimized](https://github.com/PyPSA/pypsa-eur/blob/df2425d4a04648e948d8291421cab7d2ca36529f/scripts/solve_operations_network.py#L60) in `solve_operations_network.py` does what one would expect for lines, generators and storages: Take the `p_nom_opt` (or `s_nom_opt`) value from the optimized network, put it into `p_nom` (or `s_nom`) for the network to be optimized, and disallow all expansion.

However, for links, [all links with carriers other than `DC` are ignored](https://github.com/PyPSA/pypsa-eur/blob/df2425d4a04648e948d8291421cab7d2ca36529f/scripts/solve_operations_network.py#L74). This results in lots of those links being expanded in an operations-only optimization. I doubt that this is intended - and if it is, then I think it should be documented somewhere?

**Comment by fneum** [comment]
Sorry, for the delay. Yes, this should be fixed, see also #222.

**Comment by fneum** [comment]
closed by #244
