### ISSUE TITLE
update solve_operations_network.py

### ISSUE THREAD

**Issue by StuttgartYang** [PyPSA/pypsa-eur#222]
## Checklist

- [ ] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [ ] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

In solve_operations_network.py: def set_parameters_from_optimized(n, n_optim)
Line 74: links_dc_i = n.links.index[n.links.carrier == 'DC'] 
should be changed into links_dc_i = n.links.index[n.links.p_nom_extendable]

Except DC carrier, there are some other carriers which have p_nom_extendable==True

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
<paste here>
```

**Comment by fneum** [comment]
Fair enough, would you mind preparing a small PR to get the credit for this?

**Comment by fneum** [comment]
closed by #244
