### ISSUE TITLE
Natura clipped in southern Spain/Italy/Greece

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#223]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

The natura data retrieved from [zenodo](https://zenodo.org/record/3518215/) does not cover the whole cutout on land. Some regions in southern Spain, Italy and Greece are getting eligible areas where there shouldn't be. 

The figure shows the cut in region `1641`

![natura-cut](https://user-images.githubusercontent.com/19226431/109319540-43318380-784f-11eb-9413-e83fdf60f725.png)
 
In the original natura data, the red areas continue. This requires an update of the natura tiff file.

**Comment by fneum** [comment]
Ah, good catch. If you provide me with the raster file, I'll update it on zenodo.

**Comment by fneum** [comment]
closed via #224
