### ISSUE TITLE
Remove capital_cost of existing capacity in make_summary and plot_network

### ISSUE THREAD

**Issue by Heronimonimo** [PyPSA/pypsa-eur#23]
Fix make_summary and plot_network to properly handle the capital costs of existing capacity.

**Comment by coroa** [comment]
Refer also to discussion in https://github.com/PyPSA/pypsa-eur/pull/21/commits/3eb4749f13b62db856e517a3ae089efc13bdf27d.

**Comment by fneum** [comment]
We settled on including the capital cost of existing and expanded components.
