### ISSUE TITLE
Error in rule build_shapes:  jobid: 7

### ISSUE THREAD

**Issue by eromano2016** [PyPSA/pypsa-eur#230]
## Checklist

- [Y] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [Y] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Installing and running the Tutorial config of pyPSA-EUR as described. Unfortunately, I am meeting the following error on a OSX  running Mojave. I am using PyCharm and Conda for my creating my environments. 

Any idea with this is happening ? 

Thanks for your help

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       add_electricity
        1       add_extra_components
        1       base_network
        1       build_bus_regions
        1       build_powerplants
        4       build_renewable_profiles
        1       build_shapes
        1       cluster_network
        1       prepare_network
        1       retrieve_cutout
        1       retrieve_natura_raster
        1       simplify_network
        1       solve_network
        16
Select jobs to execute...

[Sat Mar 13 15:44:06 2021]
rule build_shapes:
    input: data/bundle/naturalearth/ne_10m_admin_0_countries.shp, data/bundle/eez/World_EEZ_v8_2014.shp, data/bundle/NUTS_2013_60M_SH/data/NUTS_RG_60M_2013.shp, data/bundle/nama_10r_3popgdp.tsv.gz, data/bundle/nama_10r_3gdp.tsv.gz, data/bundle/ch_cantons.csv, data/bundle/je-e-21.03.02.xls
    output: resources/country_shapes.geojson, resources/offshore_shapes.geojson, resources/europe_shape.geojson, resources/nuts3_shapes.geojson
    log: logs/build_shapes.log
    jobid: 7
    resources: mem=500

Traceback (most recent call last):
  File "/Users/eromano/PycharmProjects/pypsa-eur-master/.snakemake/scripts/tmpmnirhu7l.build_shapes.py", line 227, in <module>
    country_shapes = countries()
  File "/Users/eromano/PycharmProjects/pypsa-eur-master/.snakemake/scripts/tmpmnirhu7l.build_shapes.py", line 118, in countries
    df = gpd.read_file(snakemake.input.naturalearth)
  File "/opt/anaconda3/envs/pypsa-eur/lib/python3.8/site-packages/geopandas/io/file.py", line 127, in _read_file
    _check_fiona("'read_file' function")
  File "/opt/anaconda3/envs/pypsa-eur/lib/python3.8/site-packages/geopandas/io/file.py", line 42, in _check_fiona
    raise ImportError(
ImportError: the 'read_file' function requires the 'fiona' package, but it is not installed or does not import correctly.
Importing fiona resulted in: dlopen(/opt/anaconda3/envs/pypsa-eur/lib/python3.8/site-packages/fiona/ogrext.cpython-38-darwin.so, 2): Library not loaded: @rpath/libtbb.dylib
  Referenced from: /opt/anaconda3/envs/pypsa-eur/lib/libtiledb.dylib
  Reason: image not found
[Sat Mar 13 15:44:07 2021]
Error in rule build_shapes:
    jobid: 7
    output: resources/country_shapes.geojson, resources/offshore_shapes.geojson, resources/europe_shape.geojson, resources/nuts3_shapes.geojson
    log: logs/build_shapes.log (check log file(s) for error message)

RuleException:
CalledProcessError in line 122 of /Users/eromano/PycharmProjects/pypsa-eur-master/Snakefile:
Command 'set -euo pipefail;  /opt/anaconda3/envs/pypsa-eur/bin/python3.8 /Users/eromano/PycharmProjects/pypsa-eur-master/.snakemake/scripts/tmpmnirhu7l.build_shapes.py' returned non-zero exit status 1.
  File "/opt/anaconda3/envs/pypsa-eur/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2326, in run_wrapper
  File "/Users/eromano/PycharmProjects/pypsa-eur-master/Snakefile", line 122, in __rule_build_shapes
  File "/opt/anaconda3/envs/pypsa-eur/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/opt/anaconda3/envs/pypsa-eur/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/opt/anaconda3/envs/pypsa-eur/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/opt/anaconda3/envs/pypsa-eur/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/eromano/PycharmProjects/pypsa-eur-master/.snakemake/log/2021-03-13T154405.273426.snakemake.log


```

**Comment by eromano2016** [comment]
I am also adding the list of package as published by Conda list

affine                    2.3.0                      py_0    conda-forge
aiohttp                   3.7.4            py38h96a0964_0    conda-forge
amply                     0.1.4                      py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.2            py38h50d1736_1    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
atlite                    0.0.3                      py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
blosc                     1.21.0               h046ec9c_0    conda-forge
bokeh                     2.3.0            py38h50d1736_0    conda-forge
boost-cpp                 1.72.0               hdf9ef73_0    conda-forge
boto                      2.49.0                     py_0    conda-forge
boto3                     1.17.27            pyhd8ed1ab_0    conda-forge
botocore                  1.20.27            pyhd8ed1ab_0    conda-forge
bottleneck                1.3.2            py38hc7193ba_3    conda-forge
brotlipy                  0.7.0           py38h5406a74_1001    conda-forge
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.8                hc929b4f_4    conda-forge
c-ares                    1.17.1               h0d85af4_1    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
cachetools                4.2.1              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            hec6a9b0_1003    conda-forge
cartopy                   0.17.0          py38h9bcff04_1015    conda-forge
cdsapi                    0.5.1                    pypi_0    pypi
certifi                   2020.12.5        py38h50d1736_1    conda-forge
cffi                      1.14.5           py38ha97d567_0    conda-forge
cfitsio                   3.470                h01dc385_7    conda-forge
cftime                    1.4.1            py38ha1b04c9_0    conda-forge
chardet                   4.0.0            py38h50d1736_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
coincbc                   2.10.5               he509fd4_1    conda-forge
conda                     4.9.2            py38h50d1736_0    conda-forge
conda-package-handling    1.7.2            py38h94c058a_0    conda-forge
configargparse            1.3                pyhd8ed1ab_0    conda-forge
countrycode               0.2                      pypi_0    pypi
cryptography              3.4.6            py38h1fa4640_0    conda-forge
curl                      7.75.0               h06286d4_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py38h5406a74_3    conda-forge
dask                      2021.3.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.3.0           pyhd8ed1ab_0    conda-forge
datrie                    0.8.2            py38h4d0b108_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
distributed               2021.3.0         py38h50d1736_0    conda-forge
docutils                  0.16             py38h50d1736_3    conda-forge
entsoe-py                 0.2.10                     py_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.10               h1c7c35f_0    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
fiona                     1.8.13           py38he71f6a4_0    conda-forge
fontconfig                2.13.1            hd23ceaa_1004    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
freexl                    1.0.6                h0d85af4_0    conda-forge
fsspec                    0.8.7              pyhd8ed1ab_0    conda-forge
gdal                      3.0.4           py38h9f7df5a_10    conda-forge
geographiclib             1.50                       py_0    conda-forge
geokit                    1.1.2                    pypi_0    pypi
geopandas                 0.9.0              pyhd8ed1ab_0    conda-forge
geopy                     2.1.0              pyhd3deb0d_0    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
geotiff                   1.6.0                hd8796ba_0    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
gitdb                     4.0.5              pyhd8ed1ab_1    conda-forge
gitpython                 3.1.14             pyhd8ed1ab_0    conda-forge
glaes                     1.1.2                    pypi_0    pypi
glib                      2.66.7               he49afe7_1    conda-forge
glib-tools                2.66.7               he49afe7_1    conda-forge
google-api-core           1.25.1             pyhd8ed1ab_0    conda-forge
google-auth               1.24.0             pyhd3deb0d_0    conda-forge
google-cloud-core         1.5.0              pyhd3deb0d_0    conda-forge
google-cloud-storage      1.35.0             pyhd3deb0d_0    conda-forge
google-crc32c             1.1.2            py38haea9d43_0    conda-forge
google-resumable-media    1.2.0              pyhd3deb0d_0    conda-forge
googleapis-common-protos  1.52.0           py38h50d1736_1    conda-forge
grpcio                    1.36.1           py38ha263829_0    conda-forge
hdf4                      4.2.13            h71d84a9_1004    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.7.2            py38h50d1736_0    conda-forge
ipython                   7.21.0           py38h9bb44b7_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.18.0           py38h50d1736_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
json-c                    0.13.1            h575e443_1002    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_core              4.7.1            py38h50d1736_0    conda-forge
kealib                    1.4.14               h31dd65d_2    conda-forge
kiwisolver                1.3.1            py38hd9c93a9_1    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
libarchive                3.5.1                h078526d_0    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcrc32c                 1.1.1                h1c7c35f_2    conda-forge
libcurl                   7.75.0               h8ef9fac_0    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libdap4                   3.20.6               h75eb3ff_1    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgdal                   3.0.4               h242383b_10    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_19    conda-forge
libgfortran5              9.3.0               h6c81a4c_19    conda-forge
libglib                   2.66.7               hd556434_1    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h88bc94a_1012    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libnetcdf                 4.7.4           nompi_h9d8a93f_107    conda-forge
libnghttp2                1.43.0               h07e645a_0    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     12.3                 h7049927_3    conda-forge
libprotobuf               3.15.6               hcf210ce_0    conda-forge
libsolv                   0.7.17               hfd3ada9_0    conda-forge
libspatialindex           1.9.3                h1c7c35f_3    conda-forge
libspatialite             4.3.0a            h658e6c1_1038    conda-forge
libssh2                   1.9.0                h52ee1ee_6    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libwebp-base              1.2.0                hbcf498f_0    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
llvm-openmp               11.0.1               h7c73e74_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.6.2            py38h7d97eb6_1    conda-forge
lz4-c                     1.9.2                hb1e8313_3    conda-forge
lzo                       2.10              haf1e3a3_1000    conda-forge
mamba                     0.8.2            py38h0c98490_0    conda-forge
markupsafe                1.1.1            py38h5406a74_3    conda-forge
matplotlib-base           3.3.4            py38hb24f337_0    conda-forge
memory_profiler           0.58.0                     py_0    conda-forge
mock                      4.0.3            py38h50d1736_1    conda-forge
msgpack-python            1.0.2            py38hd9c93a9_1    conda-forge
multidict                 5.1.0            py38h5406a74_1    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
netcdf4                   1.5.6           nompi_py38h1f593c7_100    conda-forge
networkx                  2.5                        py_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
numexpr                   2.7.3            py38h1588c1c_0    conda-forge
numpy                     1.19.0           py38h598c1e0_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.3.1                h6cbf5cd_3    conda-forge
openpyxl                  3.0.7              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1j               hbcf498f_0    conda-forge
owslib                    0.23.0             pyhd8ed1ab_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.3            py38h1588c1c_0    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.2            py38h83525de_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
ply                       3.11                       py_1    conda-forge
poppler                   0.87.0               h3232a60_1    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 he852019_3    conda-forge
powerplantmatching        0.4.8              pyhd8ed1ab_0    conda-forge
progressbar2              3.53.1             pyh9f0ad1d_0    conda-forge
proj                      7.0.0                h45baca5_5    conda-forge
prompt-toolkit            3.0.17             pyha770c72_0    conda-forge
protobuf                  3.15.6           py38ha048514_0    conda-forge
psutil                    5.8.0            py38h5406a74_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulp                      2.4              py38h50d1736_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycosat                   0.6.3           py38h5406a74_1006    conda-forge
pycountry                 20.7.3             pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pykdtree                  1.3.4            py38hf3d72b9_0    conda-forge
pyomo                     5.7.3            py38h91a8764_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38h7d7e87d_0    conda-forge
pypsa                     0.17.1             pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py38h5406a74_2    conda-forge
pyshp                     2.1.3              pyh44b312d_0    conda-forge
pysocks                   1.7.1            py38h50d1736_3    conda-forge
pytables                  3.6.1            py38hfb086ad_3    conda-forge
python                    3.8.8           h4e93d89_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-utils              2.5.5              pyh44b312d_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyutilib                  6.0.0              pyh9f0ad1d_0    conda-forge
pyyaml                    5.4.1            py38h5406a74_0    conda-forge
rasterio                  1.1.5            py38hac06332_1    conda-forge
ratelimiter               1.2.0                   py_1002    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
reproc                    14.2.1               hbcb3906_0    conda-forge
reproc-cpp                14.2.1               h2e338ed_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rsa                       4.7.2              pyh44b312d_0    conda-forge
rtree                     0.9.7            py38hc59ffc2_1    conda-forge
ruamel_yaml               0.15.80         py38hca655e8_1004    conda-forge
s3transfer                0.3.4              pyhd8ed1ab_0    conda-forge
scikit-learn              0.24.1           py38hfd19401_0    conda-forge
scipy                     1.6.0            py38ha68b950_0    conda-forge
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
setuptools                49.6.0           py38h50d1736_3    conda-forge
shapely                   1.7.1            py38h7843d1f_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sklearn                   0.0                      pypi_0    pypi
smart_open                4.2.0              pyhd8ed1ab_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snakemake-minimal         6.0.5                      py_0    bioconda
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.34.0               h17101e1_0    conda-forge
statsmodels               0.12.2           py38ha1b04c9_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tiledb                    1.7.7                h84aa2a7_2    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
toposort                  1.6                pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h5406a74_1    conda-forge
tqdm                      4.59.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
tsam                      1.1.0                    pypi_0    pypi
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzcode                    2021a                h0d85af4_1    conda-forge
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
vresutils                 0.3.1                    pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wrapt                     1.12.1           py38h5406a74_3    conda-forge
xarray                    0.17.0             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.2             h8f8adb3_1004    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
yarl                      1.5.1            py38h4d0b108_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.8                h62961b2_0    conda-forge

**Comment by cristianomariacumer** [comment]
Same issue affects me on Ubuntu 18.04 LTS

**Comment by FabianHofmann** [comment]
Hey, this will very likely be solved in #224 . For the meantime I would suggest to try get fiona properly installed, which means you have to play around with the installation of GIS packaging we are requiring. Try removing fiona/libgdal/gdal and reinstall them.

**Comment by cristianomariacumer** [comment]
Trying to re-install fiona/libgdal/gdal lead to an uncontrolled spike in the dilitium core triggering a uncontrolled core discharge.
So I took the files from the ubuntu libtbb package and copied them into the lib directory of the conda environment.

libtbbmalloc_proxy.so.2
libtbbmalloc.so.2
libtbb.so.2

Not clean, but alas, conda isn't either.

**Comment by fneum** [comment]
> uncontrolled spike in the dilitium core triggering a uncontrolled core discharge

Love the reference!

Just ran the PyPSA-Eur CI pipeline this afternoon, which ran through:

https://travis-ci.org/github/PyPSA/pypsa-eur/builds/762347499

The GIS libraries are unfortunately a bit fiddly... Have you tried mamba https://github.com/mamba-org/mamba? Might be worth a shot.

**Comment by cristianomariacumer** [comment]
Hi Fabian,

mamba works much better indeed. Thanks

**Comment by xiaomingk** [comment]
Hi guys! Is there a solution for this bug now? I faced the same error when I ran the model. Many thanks!
