### ISSUE TITLE
All TYNDP links already contained in Gridkit 

### ISSUE THREAD

**Issue by duboisa1** [PyPSA/pypsa-eur#231]
https://github.com/PyPSA/pypsa-eur/blob/9048af482fdd6cfbe7202efa5561fe6f078c7734/scripts/base_network.py#L213-L215

On restricted scope instance (e.g. BENELUX + Great Britain), I got an error further down because 'links_tyndp' was empty. After checking, this happens when comparing 'links' to 'links_tyndp' and all TYNDP links are already present in 'links'.

Would adding 
```
if links_tyndp.empty:
    return buses, links
```
just below line 215 fix this?

**Comment by FabianHofmann** [comment]
Hey @duboisa1 
Yes, that's sounds like a reasonable fix to me. Mind creating a PR? (perhaps even with a note to the release notes)
