### ISSUE TITLE
Implement support GitHub actions.

### ISSUE THREAD

**Issue by euronion** [PyPSA/pypsa-eur#239]
Implement GitHub actions for the repository.

## Describe the feature you'd like to see

Wishlist and ideas:

- [ ] black or PEP 8 automatic code formatting (`git` functionality to have continued support for blame/diff)
- [ ] jupyter notebooks without output files.
- [ ] REUSE compliance check

**Comment by euronion** [comment]
Potentially also of interest:
- Automatically publish on `conda-forge`: https://github.com/fcakyon/conda-publish-action
- Automatically publish on `pypi`: https://github.com/pypa/gh-action-pypi-publish

**Comment by FabianHofmann** [comment]
covered by #416
