### ISSUE TITLE
Add option to set number of clusters per country

### ISSUE THREAD

**Issue by Heronimonimo** [PyPSA/pypsa-eur#25]
Just thinking of the following enhancement:
Would it be possible to set the number of clusters per country? That would enable to do more detailed analysis on one country while keeping approximately right border flows.

**Comment by coroa** [comment]
In principle it's easy to implement, you would just conditionally replace the `distribute_number_of_clusters` function in the `cluster_network` script.

The tricky bit is how to encode the desired number of clusters in `config.yaml`.

And how does this information relate to the total number of clusters.

We could allow to define weights ($0 <= w_c <= 1$) for a subset of countries and distribute the remaining weight to the unconstrained countries in proportion to mean load.

**Comment by Heronimonimo** [comment]
Didn't think yet of adding weights to the clustering process, but that seems to be a very elegant method. Than you can also have different tiers of detail levels. So a very detailed core country, a bit less detailed ring around it and the rest of Europe as a one node per country. That would be a very nice enhancement!

**Comment by Heronimonimo** [comment]
Adding to this, I would suggest setting up a line directly below countries in `config.yaml` with `country_weights: [1,0.2,0.3,0.4]`. A normalized version of this could be multiplied with the load and generator capacity based weights for dividing the clusters.

**Comment by fneum** [comment]
closed in #87
