### ISSUE TITLE
Support selection of only landlocked countries

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#265]
Currently, if the user picks only landlocked countries (e.g. `['AT']`), the offshore shapes are empty which leads to an error when `geopandas` tries to write this empty GeoDataFrame to a file.

I don't have a good idea for a fix yet, since it has some downstream effects, too; e.g. `regions_offshore.geojson`. I would somehow want to avoid a case distinction in the `Snakefile`.

xref https://groups.google.com/g/pypsa/c/CgLgxBUwutw

**Comment by pz-max** [comment]
@fneum we create an [empty geojson as](https://github.com/pypsa-meets-africa/pypsa-africa/blob/1fd74e703d507a0105eaca89981efffa6ea021db/scripts/build_shapes.py#L204-L218) default and having then [case distinction within the function](https://github.com/pypsa-meets-africa/pypsa-africa/pull/341). 

This avoids any case distinction in the Snakefile.
