### ISSUE TITLE
Use 2010 as default weather year?

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#286]
2010 -> very cold -> high heat demand -> challenging for sector-coupling model -> Kalte Dunkelflaute

**Comment by euronion** [comment]
Other discussed alternative: Use a typical metereological year TMY. Refs:

* https://ec.europa.eu/jrc/en/PVGIS/tools/tmy (thanks @martavp )
* ISO 15927-4
* https://www.dwd.de/DE/klimaumwelt/klimaforschung/spez_themen/try/try_node.html

**Comment by fneum** [comment]
We now ship 2010, 2013, 2019 and 2023 as pre-built weather data cutouts, which makes it easy to use 2010 data. But we keep 2013 as default.
