### ISSUE TITLE
GLPK, CBC or lp_solve support

### ISSUE THREAD

**Issue by Heronimonimo** [PyPSA/pypsa-eur#3]
Is there a way to run the pypsa-eur model with an opensource solver like GLPK, CBC or lp_solve?

**Comment by coroa** [comment]
I suppose if you restrict yourself to a 96 buses, you stand a fair chance with cbc.

Just replace the ‘solving: solver’ section with ‘name: cbc’. Can’t help you with what settings to pick. 

Please report back if you are successful!

**Comment by Heronimonimo** [comment]
Using CBC I'm running into the following:
`RuntimeError: Selected solver is unable to handle objective functions with quadratic terms. Objective at issue: objective.`

The settings I used are:
```
solving:
  options:
    formulation: kirchhoff
    #load_shedding: true
    noisy_costs: true
    min_iterations: 4
    # max_iterations: 6
    max_iterations: 3
    #nhours: 10
    clip_p_max_pu: 0.01
  solver:
    name: cbc
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
```

**Comment by coroa** [comment]
There aren’t any quadratic terms in the objective. It’s likely CBC doesn’t understand the threads, method, etc. solver options. You should remove everything but ‘name: cbc’. Or research the corresponding options for it. As I said, I can’t help you with that.

Best

**Comment by coroa** [comment]
Perhaps, set ‘nhours: 24’ for testing the solver settings. That way the model is only solved for the first 24 time steps (ie first 3 days of January)

**Comment by Heronimonimo** [comment]
As far is I can see it hangs in the clustering phase. This is the objective function in cluster_network.py:
```
    m.objective = po.Objective(expr=po.sum((m.n[i] - L.loc[i]*n_clusters)**2
                                           for i in L.index),
                               sense=po.minimize)
```
This function is quadratic. I simply removed the "**2" to see if this is the culprit. This made me pass the clustering network phase. 

The question remaining is if there is a good way to rewrite this function to a linear variant.

**Comment by coroa** [comment]
True, i forgot about the tiny optimization problem to determine the number of buses for each country and synchronous zone. The idea is to choose as close to the mean load as possible. 

I suppose there are three possible solutions:

1. Find an open-source solver able to solve this mip with quadratic objective? (ipopt should be able to, but its hard to install)

2. Solve the problem with Gurobi or CPLEX using the NEOS service

3. Reformulate into a linear problem, ie introduce a positive variable `dn` for each `i` which must be smaller than `m.n[i] - L.loc[i]*n_clusters` and `L.loc[i]*n_clusters - m.n[i]` and minimize the sum of all `dn`, ie use an L1 rather than an L2 norm.

**Comment by Heronimonimo** [comment]
Good news!

Using ipopt I was able to solve the quadratic function. It was quite easy to setup using:
`conda install -c conda-forge ipopt 
`
Maybe it can be put in the environment.yaml and made the default solver for the clustering part?

**Comment by coroa** [comment]
Good indeed, i added a simple dynamic check to `cluster_network.py` to fall back to `ipopt`, if the chosen solver does not support quadratic objectives in commit https://github.com/PyPSA/pypsa-eur/commit/e90f0a3a6bbd269b9afc7228b4a9955bd317fcc3 .

Thus, one can choose `cbc` in `config.yaml` for all the way now.

Which version of `cbc` are you using? Which networks are you able to solve? Did you add any solver options to `solving: solver`? How big is memory use for you (ie can you paste the output of `grep memory logs/*_python.log`)? And maybe `tail benchmarks/solve_network/*` to see the runtimes.

I'll probably add `cbc` and `ipopt` to `environment.yaml` then.
@nworbmot fyi.

**Comment by Heronimonimo** [comment]
That's a great addition to the code.

I'm currently using this one: https://anaconda.org/conda-forge/coincbc. Performance is not that great though. With 37 clusters and only solving for NL, BE, DE, LU and DE it is already running for 36 hours without getting trough one iteration. Is this expected behavior? Or is performance much better with gurobi?

**Comment by Heronimonimo** [comment]
Would there be a way to add in support for using NEOS? (https://neos-guide.org/neos-interfaces#pyomo)

That would probably open up the possibility to use Gurobi and CPLEX for everyone.

**Comment by coroa** [comment]
37 clusters with Gurobi takes about 15mins per iteration. So yes, performance is orders of magnitudes better with the commercial solvers.

We considered NEOS, but they have a limit on the maximum file size of 16M for the pyomo lp file. Ours is on the order of several 100M. Refer to: https://neos-guide.org/content/FAQ#submitting .

**Comment by coroa** [comment]
Note, that you could further reduce the number of clusters, if you only consider 4 countries. Try something on the order of 8.

**Comment by Heronimonimo** [comment]
Based on http://manpages.ubuntu.com/manpages/cosmic/man1/cbc.1.html I figured out the following:
```
solver:
    name: cbc
    threads: 4
    barrier:
    userClp:
    integerT: 1.e-5
    primalT: 1.e-5
    dualT: 1.e-5
    preT: 1.e-5
```
Do these make sense to you?

**Comment by coroa** [comment]
its not an integer problem, so `integerT` and `preT` don't have any effect. I'm unsure whether `barrier` works like this, or how you would choose the barrier algorithm; you can probably check if it works by inspecting the solver log files (you can find them after each successful iteration as `logs/..._solver.log`).

If `barrier` is used, it probably makes sense to add `cross: off`. It also makes sense to investigate the `chol` and `fact` keywords which configure the two main time-drain of the barrier algorithm. Unfortunately for being able to choose another `chol` factorization, you have to compile `cbc` on your own and for example link in the `libsuitesparse` library to get the `UniversityOfFloriday` cholesky implementation. Note, that even though I went down that route once, I did NOT get to acceptable computation times. Maybe you are able to figure something out, I missed though.

The best way to learn about the options in `cbc` I found is to open up its shell interface and use `?` to list all available options and f.ex. `barrier??` for at least a minimal explanation.

**Comment by Heronimonimo** [comment]
That's helpful. What I also found was that by easing the optimallity gap to 1% (by setting the option 'ratio: 0.01') the runs have sped up a little bit. Still the 'solve_network' stage takes a little over 1 hour with only 8 clusters.

Were you able to get 'cbc' running multi-threaded? Specifying 'threads: 4' doesn't seem to work, while I'm pretty sure 'cbc' was compiled with '-enable-cbc-parallel' because 'cbc' does accept the '-threads 4' option on the command line.

**Comment by coroa** [comment]
I don't know how big the LPs are in your case. While solving, I think you should find them in `.snakemake/shadow/tmp.../tmp....lp` or something like this. Otherwise you can change where pyomo stores them in the config using `solving: tmpdir`.

**Comment by coroa** [comment]
Didn't check for parallelization

**Comment by fhg-isi** [comment]
Is the combination of 
* ipopt for non-linear part cluster_network.py and
* cbc for solve_networks 
still the recommended solution?

Or should HiGHS be used?

https://ergo-code.github.io/HiGHS/dev/options/definitions/

If HiGHS is set to use default solver option "choose" ... will it be able to consider both, non-liniear and linear parts? 
Or should there be a programmed fallback-workflow, similar to the one described above for cbc?
