### ISSUE TITLE
Min/max shore distance offshore wind config handle

### ISSUE THREAD

**Issue by Heronimonimo** [PyPSA/pypsa-eur#32]
Why is the min and max shore distance an input in config.yaml to define if the optimization chooses for DC or AC connection? Should the decision between DC and AC not be made based on cost?

**Comment by nworbmot** [comment]
The limiting factor is not material cost the way it is currently calculated but the reactive power requirements for very long subsea AC cables. For AC, the length causes voltage problems and high losses for very long cables. This is why long subsea cables are always HVDC. We cannot capture reactive power in the linear optimisation, so instead we have a shore distance limit. Based on existing wind park configurations, this should probably be set at 50 km. I will open a new issue on this. Maybe we should close this issue if you agree.

**Comment by fneum** [comment]
#34

**Comment by fneum** [comment]
This is also related to #34
