### ISSUE TITLE
Workflow improvement: Support new EIA data format in build_hydro

### ISSUE THREAD

**Issue by euronion** [PyPSA/pypsa-eur#324]
The EIA data format from our datasource changed. Suggestions
- Automatic download of EIA data OR update the EIA .csv file with hydro generation to new dataformat
- substitute the `vresutils` dependency in `build_hydro` by writing the `pd.read_csv` statement directl.y

_Originally posted by @euronion in https://github.com/PyPSA/pypsa-eur/pull/321#issuecomment-1059728440_

**Comment by fneum** [comment]
This was addressed in #342.

Keep open until #347 is in via #342.
