### ISSUE TITLE
Minor error: Germany refered as 'BE' in config.tutorial.yaml

### ISSUE THREAD

**Issue by duboisa1** [PyPSA/pypsa-eur#362]
Just a minor error noticed while reading the tutorial.

In the 'How to customise PyPSA-Eur?' section, after the sentence:
'The model can be adapted to only include selected countries (e.g. Germany) instead of all European countries to limit the spatial scope.',
the country list contains the code 'BE' instead of 'DE'.

Looking at the docs/tutorial.rst file, the error comes from the config.tutorial.yaml where countries is set to ['BE'] instead of ['DE'].

https://github.com/PyPSA/pypsa-eur/blob/5fd99628c97ac2f174259d890fa6999449ea8a23/config.tutorial.yaml#L20

**Comment by fneum** [comment]
Yeah, we recently switched from Germany to Belgium in the tutorial/testing to reduce load on the CI because it's a smaller country. Fixed via 3acc4a22360cbf6c3f22c63880f55c465ee8244b
