### ISSUE TITLE
Support for Apple M1 Architecture (`osx-arm64`)

### ISSUE THREAD

**Issue by zoltanmaric** [PyPSA/pypsa-eur#385]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Running `conda env create -f envs/environment.yaml` on a Mac computer with an Apple M1 processor fails with the below error message. `pyomo` and `tabula-py` are platform-specific, and they weren't built for the `osx-arm64` architecture.

## Error Message

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - tabula-py
  - pyomo

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by zoltanmaric** [comment]
## Short-Term Fix
I temporarily resolved the issue by installing `tabula-py` and `pyomo` with `pip`, as the architecture-specific wheels _were_ available. It also required installing `pypsa` with `pip`, otherwise `pypsa` couldn't resolve the dependencies correctly, as mentioned in https://github.com/PyPSA/pypsa-eur/issues/142#issuecomment-1154056216

## Long-Term Fix
I also managed to create the conda packages for `tabula-py` and `pyomo` as described in [the official Conda forge documentation](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock), simply by adding `pyomo` and `tabula-py` to the `conda-forge-pinning` list in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2986, and a minor fix in `tabula-py` in https://github.com/conda-forge/tabula-py-feedstock/pull/24

## GitHub Workflow for `osx-arm64` Builds
I wanted to offer to set up an additional GitHub workflow for the `osx-arm64` architecture, but according to this comment in https://github.com/actions/virtual-environments/issues/2187#issuecomment-1164711613, GitHub will only add support for `osx-arm64` virtual machines by the end of fiscal year 2022.

Instead, I'm adding this issue for documentation, in case in the future some additional architecture-specific packages get added, which don't have a conda package for `osx-arm64`.

**Comment by fneum** [comment]
Fantastic! We’ll add M1 to the CI once available.
