### ISSUE TITLE
Installing snakemake via environment.yaml for Windows

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#39]
Snakemake can not be installed from `conda` in Windows.

Either provide another environment file; e.g. `environment_windows.yaml`

or follow (after removing snakemake from environment.yaml):

```bash
conda env create -f environment.yaml
conda activate pypsa-eur
conda install datrie
pip install snakemake
```

**Comment by coroa** [comment]
Separate ‘environment.yaml’ for windows is the way to go

**Comment by coroa** [comment]
Turns out, that there is a separate `snakemake-minimal` package which does not pull in most of the remote file handlers and also avoids the critical pygraphviz dependency. An `environment.yaml` where `snakemake` is replaced by `snakemake-minimal` should work on all architectures.
