### ISSUE TITLE
Unkown values in powerplantmachting data

### ISSUE THREAD

**Issue by lisazeyen** [PyPSA/pypsa-eur#408]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

with the newest version of pypsa-eur there are unkown values for DateIn and DateOut in the powerplantmatching data. This issue is not connected to the version of the powerplantmatching. If I understand correctly actually the missing data should be filled with some heuristic [here](https://github.com/PyPSA/pypsa-eur/blob/f5fd5299dd0a37b5a67c632ca905d779f593f28d/scripts/build_powerplants.py#L116). With pypsa-eur at commit cc1c9fd75297305cc4b171aba1841e4c72bef414 the filling of the unkown values is still working (also with the newer version of the powerplantmachting package)

@FabianHofmann any ideas where the error is comming from?

**Comment by fneum** [comment]
@FabianHofmann, do you think this fixed itself?

**Comment by FabianHofmann** [comment]
@fneum not sure, I don't think so... @lisazeyen you know if that bug still persists?

**Comment by lisazeyen** [comment]
We can close this issue. It seems to be resolved.
