### ISSUE TITLE
HVDC links being removed in simplify_network.py

### ISSUE THREAD

**Issue by paulregg** [PyPSA/pypsa-eur#411]
## Checklist

- [ X ] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [ X ] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug
Hi Fabian,

I was reading your paper on hydrogen networks in PyPSA-Eur-Sec, and I noticed that my model runs install way less wind generation in Ireland than the models in the paper. I then noticed that no HVDC connection exists in my network between Ireland and Britain, which I think would be the reason for this, since all the electricity generated would have to go through Northern Ireland and Scotland.

I've been struggling to figure out why this HVDC connection is removed. I checked, and in pypsa-eur, it exists in [base.nc](http://base.nc/) and [elec.nc](http://elec.nc/), but is removed in [elec_s.nc](http://elec_s.nc/). Therefore, it must be happening in simplify_network.py, probably in the simplify_links() function, but I can't figure out why the connection would be stripped here.

I don't know if this is something you've seen before, and it's probably difficult without seeing what's happening on my machine, but I thought I'd check if you have any advice. I'm currently rerunning the pypsa-eur to recreate [elec_s.nc](http://elec_s.nc/), but it's taking a long time because it triggered a recreation of renewable resources.

I'm using wildcard simpl = ""

The link has index '14815'
in simplify_network.py, node 5937 is found to be a stub and deleted, which results in the DC link being deleted. 

I've also checked, and node 5937 is not a stub, so I don't know why this is occurring. It turns out node 5935 in [elec.nc](http://elec.nc/) is a stub, with only one connection (to 5937, the GB side of the IE-GB link). Therefore, in the busmap_by_stubs() function, first 5935 then 5937 is added to the stub list.

I've checked, and 5935 is a stub in [base.nc](http://base.nc/) as well.

I haven't looked in detail into other links, but by comparing my results and the 2022 Hydrogen network paper, I notice several that might be removed as well:
Scotland - Norway
3rd cross-channel UK-FR connection (near Portsmouth)
UK-NL
Denmark-NL
UK-Denmark

from config.yaml :

clustering:
  simplify_network:
    to_substations: false # network is simplified to nodes with positive or negative power injection (i.e. substations or offwind connections)
    algorithm: kmeans # choose from: [hac, kmeans]
    feature: solar+onwind-time

links:
  p_max_pu: 1.0
  p_nom_max: .inf
  include_tyndp: true
  under_construction:

## Error Message

No error message, since network still functions normally without the missing links

**Comment by pz-max** [comment]
Hi @paulregg , sorry for the late response some of us were on holiday. Thank you for the bug report. Seems like something is going wrong. We will discuss the issue and provide you with more feedback.

**Comment by fneum** [comment]
closed via 27d4af8e6574d8b39f1a442caa37d896ff1ae876

was indeed a bug related to the new ENTSO-E grid extract, required a few manual corrections
