### ISSUE TITLE
update environment for RTD

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#426]
From RTD:

Your project "pypsa-eur" is using a deprecated feature to force using Mamba instead of Conda. You need to update your config file to use the new ["build.tools.python"](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python) key with "mambaforge-4.10" as value before May 1st, 2022 to keep using Mamba as your environment builder. Please, read more about our [config file](https://docs.readthedocs.io/en/stable/config-file/v2.html) if you are not using one already.

**Comment by fneum** [comment]
Not up to date, is it? Documentation building doesn't use mamba/conda for PyPSA-Eur. Maybe some branch is left.
