### ISSUE TITLE
deprecate -m ending for clustering?

### ISSUE THREAD

**Issue by martacki** [PyPSA/pypsa-eur#428]
## Describe the feature you'd like to see

With PR #415, the current ending `-m` in the clustering (e.g. `elec_s_45m.nc`) seems odd. I'd suggest to remove this option, and either substitute this with the possibility to write `renewables` into `exclude_carriers` in the config, or simply remove it without substitution. In the latter, users have to manually input which carriers shouldn't be clustered without the default suggestion of the `-m` ending. I have the feeling that maintaining this `-m` option is cumbersome even for developers, and I don't have the impression that it is being used.

What do others think?

**Comment by fneum** [comment]
I just looked into this again. I don't think there is a benefit to remove it (it's just 3 lines of code), whereas we loose some functionality as mentioned above.

However, I have made a small adjustment in #479 that aligns it to the `exclude_carrier` functionality.
