### ISSUE TITLE
Provide `Dockerfile` and docker image for quick start

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#43]
The idea is to provide a `Dockerfile` in the PyPSA-Eur repository for tutorials (and maybe continuous integration) that contains
- the `pypsa-eur` environment provided in `environment.yaml`
- an already extracted data bundle (e.g. minimal data bundle #40)
- an open-source solver or commercial solver (e.g. like Gurobi) without a license

One could then run everything from the docker image without having to install and copy the data bundles.

One can copy results for post-processing to the host with
```shell
docker cp CONTAINER-ID:/docker-container/source-path /host/target-path
```
One can get a list of `CONTAINER-ID`s with `docker ps`.
Copying also works vice-versa (e.g. copying a modified `config.yaml` or a Gurobi license file)

Open questions:
- [x] Can we use a minimal data-bundle docker image and open-source solvers for continuous integration (#40)? This way the image would have a twofold use to us: tutorials and CI. YES
- [x] It probably would not make much sense to provide a docker image with the full data bundle and only an open-source solver. Maybe a complete data-bundle and a Gurobi installation -- where the user has to copy the Gurobi license file if Gurobi is selected -- is a viable way?
- [x] Where to host the docker image? [Docker Hub](https://hub.docker.com/) or own public repository?

**Comment by fneum** [comment]
Most likely we would have to rely on open-source solvers for this since Gurobi requires a floating license for Docker images:
```
GurobiError: Must use a floating license for a Docker container
```
I have tried the following:
- install Gurobi without a license in a Docker image that has all of `pypsa-eur` downloaded/extracted/environments...
- ask the user to provide a license key when starting up the docker image:
```bash
docker run -it -e 'GUROBI_LICENSE=XXXXXXXXX' pypsa-eur-public bash
```
Which works, but when running a simple model it complains and asks for a floating license.

**Still in combination with a minimal data-bundle, a Docker image with only an open-source solver would make sense?**

An intermediary step to reduce the number of manual steps for installation could be an installation script like

```bash
#!/bin/bash

# after `git clone https://github.com/PyPSA/pypsa-eur.git` and `cd pypsa-eur`

echo "Downloading data bundles"
curl -L "https://vfs.fias.science/d/0a0ca1e2fb/files/?dl=1&p=/pypsa-eur-data-bundle.tar.xz" -o "./pypsa-eur-data-bundle.tar.xz"
curl -L "https://vfs.fias.science/d/0a0ca1e2fb/files/?dl=1&p=/pypsa-eur-cutouts.tar.xz" -o "./pypsa-eur-cutouts.tar.xz"
curl -L "https://vfs.fias.science/d/0a0ca1e2fb/files/?p=/natura.tiff&dl=1" -o "./resources/natura.tiff"

echo "Extracting data bundles"
tar xJf ./pypsa-eur-data-bundle.tar.xz -C ./data
tar xJf ./pypsa-eur-cutouts.tar.xz

echo "Removing zipped data bundles"
rm -rf "./pypsa-eur-cutouts.tar.xz"
rm -rf "./pypsa-eur-data-bundle.tar.xz"

echo "Installing conda environment"
conda env create -f environment.yaml

# now can do: conda activate pypsa-eur
```

Is that sensible? I am not yet convinced. If it works, it's nice; but not really nice if it fails in between.

**Comment by coroa** [comment]
> Still in combination with a minimal data-bundle, a Docker image with only an open-source solver would make sense?

It does make sense, I think. Let's restrict in the data bundle to a single day. Then I am pretty sure, even cbc should find a solution.

If you have a running model, you could try setting the `solving` config to:
```yaml
solving:
  options:
    formulation: kirchhoff
    noisy_costs: true
    min_iterations: 3
    max_iterations: 3
    clip_p_max_pu: 0.01
    nhours: 24
  solver:
    name: cbc
```

to test.

**Comment by Heronimonimo** [comment]
Having done multiple runs with both cbc and CPLEX I must say the performance difference between the two is quite dramatic. Therefore I honestly doubt it makes sense to put much effort in making a docker image when it can only be used with cbc.

The initial installation script on the other hand would be a great improvement!

**Comment by fneum** [comment]
Don't think this is necessary or helpful anymore.
