### ISSUE TITLE
New test pipeline

### ISSUE THREAD

**Issue by pz-max** [PyPSA/pypsa-eur#432]
## Describe the feature you'd like to see

Problem: Currently, we need to update the `test/config.test1.yaml` which is basically a special version of the `config.tutorial.yaml`. Further, adding new tests is quite annoying since there will be a lot of code duplication in the config.

Solution: Instead of duplicating the tutorial version for each test, we could build it from the `config.tutorial.yaml`.

This enables:
- Creating multiple tests/ more test coverage of functionalities because the test config is super small
- One disadvantage is that multiple test would require more time in the CI

Check out the recent PyPSA-Earth PR to see what is required for the new test pipeline: https://github.com/pypsa-meets-earth/pypsa-earth/pull/466 We only test the full option set for Linux to avoid long CI times.

**Comment by fneum** [comment]
You can mirror https://github.com/PyPSA/pypsa-eur-sec/pull/282 to minimise code.

**Comment by pz-max** [comment]
Thanks @fneum this is interesting.

It seems you can overwrite the config.default.yaml by `snakemake --configfile`
```python
snakemake --configfile config.default.yaml
snakemake --configfile test/config.overnight.yaml
```

Looking into the snakemake code of  `snakemake --configfile` they utilize a function called [`update_config`](https://github.com/snakemake/snakemake/blob/83ffe08d15bd338d60723a453e54b5924289c0d8/snakemake/workflow.py#L1271-L1293), which practically runs the same update as we do. Compare [snakemake](https://github.com/snakemake/snakemake/blob/83ffe08d15bd338d60723a453e54b5924289c0d8/snakemake/utils.py#L484-L505) `update_config` to our [PyPSA-Earth `update`](https://github.com/pypsa-meets-earth/pypsa-earth/blob/f363cfcbf1b59ff46de5cb3083536eef3bfa644b/scripts/build_test_configs.py#L20-L26) function.

The only difference is that snakemake uses [yaml](https://github.com/snakemake/snakemake/blob/83ffe08d15bd338d60723a453e54b5924289c0d8/snakemake/io.py#L1672) while we use `ruaml.yaml`. See what the difference is [here](https://yaml.readthedocs.io/en/latest/overview.html). I am unsure about the exact details, but when I implemented ruamel.yaml, it allowed us to export the compiled test configs and analyse them better. The rule allowing this is [`build_test_configs`](https://github.com/pypsa-meets-earth/pypsa-earth/blob/f363cfcbf1b59ff46de5cb3083536eef3bfa644b/Snakefile#L715-L732). **One questions could be: Do we really need to see the test configs? If we create new tests, how to build the test config?**

Proposal 1. Keep `build_test_configs` rule incl function. CI would look like this:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/f363cfcbf1b59ff46de5cb3083536eef3bfa644b/.github/workflows/ci-linux.yaml#L64-L76

Proposal 2. No need to build test configs locally. This saves one function [`build_test_config.py` ](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/scripts/build_test_configs.py). CI would look like this in PyPSA-Earth example:
```python
    - name: Test tutorial workflow
      run: |
        snakemake --configfile config.tutorial.yaml
        snakemake --configfile test/config.tutorial_noprogress.yaml
        snakemake --cores all solve_all_networks --forceall

    - name: Test custom workflow
      run: |
        snakemake --configfile config.tutorial.yaml
        snakemake --configfile test/config.custom.yaml
        snakemake --cores all solve_all_networks --forceall
```

Note. To my knowledge, you always need to start with `snakemake --configfile config.tutorial.yaml` to overwrite the basic tutorial options. A `--forceall` should make sure things are running from scratch. In this context, I am unsure what `snakemake -call` does & couldn't find documentation on that quickly.
