### ISSUE TITLE
Issue with snakemake SSL error on Linux machine

### ISSUE THREAD

**Issue by Rock910** [PyPSA/pypsa-eur#459]
## Checklist
- [X ] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [ X] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

Running command from the tutorial: 
snakemake -j 1 results/networks/elec_s_6_ec_lcopt_Co2L-24H.nc

## Error Message
Building DAG of jobs...
InputFunctionException in file /home/ubuntu/pypsa-eur/Snakefile, line 304:
Error:
  WorkflowError:
    Failed to evaluate default resources value 'max(2*input.size_mb, 1000)'.
        String arguments may need additional quoting. Ex: --default-resources "tmpdir='/home/user/tmp'".
    SSLError: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/6953563/files/shipdensity_global.zip (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))

**Comment by fneum** [comment]
Hi @Rock910, looks to me like a Snakemake issue. Are you running the latest Snakemake version? Otherwise, could you try successively downgrading Snakemake?

**Comment by fneum** [comment]
Assuming this has resolved itself. Please reopen if that is not the case.
