### ISSUE TITLE
Set lifetime for conventional powerplants

### ISSUE THREAD

**Issue by Heronimonimo** [PyPSA/pypsa-eur#48]
The powerplants.csv already includes a 'YearCommisioned' and 'Retrofit' column. This could be used, combined with a Fueltype and Technology to for example remove all plants older than x  for CCGT, y for Hydro, z for Coal, etc.

Would `def attach_conventional_generators(n, costs, ppl):` in `add_electricity.py` be the right place to do this? And could the year from costs specifier in config.yaml be used to calculate all plant ages?

Furthermore a .csv with lifetime per Technology and Fueltype should be included. ALso in the powerplant dataset a lot of values are missing. Are there currently plans to update this set?

**Comment by FabianHofmann** [comment]
Hey, after long time:
* powerplantmatching allows to apply rough heuristics to fill missing commissioning years, via 
        
        p = pm.powerplants()
        p = p.powerplant.fill_missing_commyears()

* there are only estimated per lifetimes per `Fueltype` in ppm, can be accessed via

        p['Lifetime'] = p.Fueltype.map(pm.get_config()['fuel_to_lifetime'])

    perhaps even more convenient would be to 

        p['YearShutdown'] = p.YearCommissioned + p.Lifetime

**Comment by fneum** [comment]
Is this possible with the powerplantmatchin update and the pd.query?

**Comment by FabianHofmann** [comment]
yes, it is :) I'll make a PR for this tomorrow.

**Comment by Heronimonimo** [comment]
Cool to see so much activity. This addition would be very much appreciated!
