### ISSUE TITLE
Readthedocs complains about outdated mamba directive (deadline: May 1st, 2022)

### ISSUE THREAD

**Issue by coroa** [PyPSA/pypsa-eur#481]
When i login to readthedocs.org i am being warned that

> Your project "pypsa-eur" is using a deprecated feature to force using Mamba instead of Conda. You need to update your config file to use the new ["build.tools.python"](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python) key with "mambaforge-4.10" as value before May 1st, 2022 to keep using Mamba as your environment builder. Please, read more about our [config file](https://docs.readthedocs.io/en/stable/config-file/v2.html) if you are not using one already.

Can someone please investigate what that means and what needs to be updated!

Thanks

**Comment by fneum** [comment]
How curious. I don't think any of the PyPSA repositories still uses `mamba/conda`, all `pip` nowadays. Also I don't see the warning. Where did you see it?

**Comment by FabianHofmann** [comment]
https://readthedocs.org/projects/pypsa-eur/

**Comment by FabianHofmann** [comment]
Just guessing, can it be because of `system_packages` set to True in `.readthedocs.yml`?

**Comment by coroa** [comment]
> How curious. I don't think any of the PyPSA repositories still uses mamba/conda, all pip nowadays. Also I don't see the warning. Where did you see it?

Main page of https://readthedocs.org/ after logging in. Prominently on the top. Since it had an x, i clicked it away. Hasn't reappeared. It was the first time i logged in after some 2 years. It's quite possible this was a notification that they sent out somewhen last year and it took some time to get to me, but is not valid anymore.

Let's assume that was the case. Deadline has passed long ago anyway.
