### ISSUE TITLE
Snapshots: Config and post processing mismatch 

### ISSUE THREAD

**Issue by Rock910** [PyPSA/pypsa-eur#483]
## Checklist

- [ X] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [X ] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*
I've changed my config.yml file modfying the snapshots and number of clusters. I run snakemake in the straightforward manner "snakemake -j 1" and get an .nc file as output. I then use python to do network analysis: network.snapshots and regardless of the year that I've set as snapshots in my config, I get the year 2013 as output in my network analysis. Am I doing something wrong?

Thanks!

**Comment by fneum** [comment]
When you change the year, you need to rerun most of the workflow.
ˋˋˋ
snakemake -j 1 -F
ˋˋˋ
