### ISSUE TITLE
Adapt plotting scripts for `cartopy`

### ISSUE THREAD

**Issue by Heronimonimo** [PyPSA/pypsa-eur#50]
When making a plot I get the error:
```
INFO:pypsa.io:Imported network elec_s_32_lc1.0_Ep-3H-CCL.nc has buses, carriers, generators, lines, links, loads, storage_units
WARNING:pypsa.plot:argument `basemap` is deprecated, use `geomap` instead.
Traceback (most recent call last):
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmpjr9460ee.plot_network.py", line 118, in <module>
    ax=ax)
  File "/home/.conda/envs/pypsa-eur/lib/python3.7/site-packages/pypsa/plot.py", line 181, in plot
    'The passed axis is not a GeoAxesSubplot. You can '
AssertionError: The passed axis is not a GeoAxesSubplot. You can create one with:
import cartopy.crs as ccrs
fig, ax = plt.subplots(subplot_kw={"projection":ccrs.PlateCarree()})
```
This started happening after updating my conda. Maybe due to recent changes in pypsa?

**Comment by fneum** [comment]
In PyPSA v0.14.0 we changed from `basemap` to `cartopy` for plotting country shapes and choosing projections (https://pypsa.org/doc/release_notes.html). This change is not yet reflected in `PyPSA-Eur`. 

All plots of a map should create axes like that
```python
fig, ax = plt.subplots(subplot_kw={"projection":ccrs.PlateCarree()})
```
Particularly the `subplot_kw` argument is important to specify the projection.

**Comment by Heronimonimo** [comment]
I just replaced the `fig, ax = ...` line by:
```
import cartopy.crs as ccrs
fig, ax = plt.subplots(subplot_kw={"projection":ccrs.PlateCarree()})
```
That seems to fix part of the problem. But now I run into two problems. 

Firstly 'OCGT-ext' and 'CCGT-ext' are not included in the new tech-colors. This can be fixed by either adding them to the list or adding some code to remove the '-ext' extension while plotting.

Secondly:
```
Traceback (most recent call last):
  File "/home/pypsa/pypsa-eur/.snakemake/scripts/tmprhs9nf08.plot_network.py", line 127, in <module>
    ax=ax)
  File "/home/.conda/envs/pypsa-eur/lib/python3.7/site-packages/pypsa/plot.py", line 173, in plot
    if use_cartopy and geomap:
UnboundLocalError: local variable 'use_cartopy' referenced before assignment
```
Unfortunately I'm not shure how to fix this second problem.

**Comment by coroa** [comment]
> I think this is a problem in plot.py that does not declare use_cartopy.

You're right, that's a PyPSA bug :(, don't know how we missed that. Just supply a `geomap = True` to the call for now!

**Comment by coroa** [comment]
I'd go with how it is done in `add_electricity` and split off the actual technology type:
```
suptech = tech.split('-')[0]
```

**Comment by Heronimonimo** [comment]
> > I think this is a problem in plot.py that does not declare use_cartopy.
> 
> You're right, that's a PyPSA bug :(, don't know how we missed that. Just supply a `geomap = True` to the call for now!

I'll try if that works.

> I'd go with how it is done in `add_electricity` and split off the actual technology type:
> 
> ```
> suptech = tech.split('-')[0]
> ```

Where should this be implemented? Or can you fix this?

**Comment by coroa** [comment]
> Where should this be implemented? Or can you fix this?

In `plot_network.py`, I can, but not today.

**Comment by Heronimonimo** [comment]
> > Where should this be implemented? Or can you fix this?
> 
> In `plot_network.py`, I can, but not today.

Not in a hurry ;)

Adding `geomap = True` to the `n.plot` call doesn't seem to fix it. Still getting a:
`UnboundLocalError: local variable 'use_cartopy' referenced before assignment`

**Comment by coroa** [comment]
Should have added, "and remove any mention of `basemap` instead".

**Comment by Heronimonimo** [comment]
Yes, that's it. Created a quick fix in #52 while we wait for the definitive fix.

**Comment by FabianHofmann** [comment]
@Heronimonimo, the current pypsa-master branch should be compatible with the status in your [PR #52](https://github.com/PyPSA/pypsa-eur/pull/52)

**Comment by Heronimonimo** [comment]
> @Heronimonimo, the current pypsa-master branch should be compatible with the status in your [PR #52](https://github.com/PyPSA/pypsa-eur/pull/52)

So the best idea would be to merge a quick fix for now that works for both those on the pypsa-master branch and those on the latest conda-forge release version?
