### ISSUE TITLE
_set_underwater_fraction fails if all links have no geometry

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#53]
I am running PyPSA-Eur for a subset of EU countries (`PL`, `EE`, `LT`, `LV`) resulting in an error during the rule `base_network`.

```
Traceback (most recent call last):
  File "pypsa-eur-baltics/.snakemake/scripts/tmpnoe9utk7.base_network.py", line 522, in <module>
    n = base_network()
  File "pypsa-eur-baltics/.snakemake/scripts/tmpnoe9utk7.base_network.py", line 489, in base_network
    _set_links_underwater_fraction(n)
  File "pypsa-eur-baltics/.snakemake/scripts/tmpnoe9utk7.base_network.py", line 424, in _set_links_underwater_fraction
    links = gpd.GeoSeries(n.links.geometry.dropna().map(shapely.wkt.loads))
  File "anaconda3/envs/pypsa-eur/lib/python3.7/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'geometry'
```

There is only one link that does not have a geometry (Since it is B2B?); i.e. `geometry` does not show up in `n.links.columns`. Once there is a link with geometry, obviously the problem disappears.

```
              bus0  bus1 carrier  p_max_pu  p_min_pu   p_nom  under_construction  ...  p_nom_max p_set  capital_cost  marginal_cost  length  terrain_factor  p_nom_opt
converter_id                                                                      ...                                                                                 
5961          5419  5411     B2B       1.0      -1.0  2000.0               False  ...        inf   0.0           0.0            0.0     0.0             1.0        0.0
```

The problematic code is here:

https://github.com/PyPSA/pypsa-eur/blob/07143fb2cd35fb2b85696b2eb7390a7e9bb46478/scripts/base_network.py#L412-L417

I would place between line 415 and 416 something like this:

```python
if not hasattr(n.links, 'geometry'):
    n.links['geometry'] = np.nan
```

Any more elegant ideas?

**Comment by FabianHofmann** [comment]
Shouldn't this rather be tackled in pypsa itself? It seems to not be proper that pypsa may use the column 'geometry' but does not supply any default for it. 
I guess adding geometry to [component_attrs/links.csv](https://github.com/PyPSA/PyPSA/blob/master/pypsa/component_attrs/links.csv) and [component_attrs/lines.csv](https://github.com/PyPSA/PyPSA/blob/master/pypsa/component_attrs/lines.csv) should solve it or?

**Comment by coroa** [comment]
Well, PyPSA doesn't really use the `geometry` column (or `underwater_fraction`, `under_construction`, `tags`, `s_nom_under_construction` and quite a few other ones). It only has the nice feature (undocumented, but carefully preserved over the `io` module rewrites) to make it easy to attach arbitrary metadata to components at the cost of maintaining the respective columns yourself; for which you have found yet another edge case where it breaks in PyPSA-Eur. There is no clear that's the right way to solve it, i fear, but will have to do with duck-tape. I'd tend towards just setting `n.links['underwater_fraction'] = 0.` if there is no geometry column.
