### ISSUE TITLE
Add H2 bus based on pop_layout fails for offshore nodes 

### ISSUE THREAD

**Issue by martavp** [PyPSA/pypsa-eur#532]
When using a high number of nodes, if any of them has no mainland area/population associated, the H2 and battery buses are not added to that node (because they are defined based on pop_layout)

https://github.com/PyPSA/pypsa-eur-sec/blob/4fd164f73ca77f2e2ec8ea9faeac2ffbfa16be61/scripts/prepare_sector_network.py#L868

This also creates some problems with the bus_map when calculating energy and energy supply in make_summary.py

https://github.com/PyPSA/pypsa-eur-sec/blob/4fd164f73ca77f2e2ec8ea9faeac2ffbfa16be61/scripts/make_summary.py#L305

https://github.com/PyPSA/pypsa-eur-sec/blob/4fd164f73ca77f2e2ec8ea9faeac2ffbfa16be61/scripts/make_summary.py#L350

**Comment by fneum** [comment]
Assuming this issue doesn't occur anymore, since it has been a long time ago.
