### ISSUE TITLE
Include option to include planned lines from ENTSO-E's TYNDP 

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/pypsa-eur#57]
The option to include the planned HVDC lines from the TYNDP was already implemented. They are in a CSV file which can be included using an optional flag. Lines can be added, and existing lines can be replaced. Lines come with a start and finish lat/lon and are attached to the closest buses.
This should be extended also to planned HVAC lines from the TYNDP, along with expected commissioning years. Extracts from the ENTSO-E map may include some of this information already, but it's not clear how complete the map is compared to the TYNDP.
FIAS colleagues have already got a list of NEP (German TYNDP) projects for Germany.

**Comment by fneum** [comment]
closed via #1085
