### ISSUE TITLE
Versioning and release notes for PyPSA-Eur

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/pypsa-eur#59]
A v0.1.0 release should be done as soon as possible.
Further regular releases should be provided, stored on zenodo, and documented with release notes (like PyPSA).

**Comment by fneum** [comment]
note to self on coupling with zenodo releases: https://guides.github.com/activities/citable-code/

**Comment by fneum** [comment]
The process is clear now and it's a continuous "issue". Therefore, closing.

**Comment by coroa** [comment]
Is there documentation on the release process, already? How does it look?

**Comment by fneum** [comment]
Roughly, my vision is:
1. Write the release notes if not already added continuously by the PRs.
2. Tag a release on github
3. Zenodo repository should ideally be updated automatically through the webhook.
4. Add network folder (which clustering levels exactly, I don't know yet) to separate Zenodo repository.

Actually, you convinced me that I should not close this issue just yet. Sorry, I have acted prematurely.
