### ISSUE TITLE
Update data in the data bundle to most up-to-date versions

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#67]
For some of the data in the data bundle newer versions are available ; e.g. for

- `data/bundle/EIA_hydro_generation_2000_2014.csv` up to 2016
- `data/bundle/NUTS_2013_60M_SH/data/NUTS_RG_60M_2013.shp` for 2016
- `data/bundle/nama_10r_3popgdp.tsv.gz` up to 2017
- `data/bundle/je-e-21.03.02.xls` up to 2017
- `data/bundle/corine/g250_clc06_V18_5.tif` with CLC 2018 https://land.copernicus.eu/pan-european/corine-land-cover/clc2018
- `data/bundle/GEBCO_2014_2D.nc` for 2019
- `data/bundle/time_series_60min_singleindex_filtered.csv` possibly
- entsoegridkit #57 #55 
- powerplantmatching #61 
-

**Comment by coroa** [comment]
`pietzker2014.xlsx` should pbb be name `pietzcker2014.xlsx` and is Supplementary data 2 from https://www.sciencedirect.com/science/article/pii/S0306261914008149

**Comment by coroa** [comment]
Updating `data/bundle/time_series_60min_singleindex_filtered.csv` will probably make some work, since the load data format changed somewhen in 2016/17 with overlapping data, which is kept in a separate column. So one will have to come up with a rule to combine the two columns to one consistent load time series.

**Comment by coroa** [comment]
For updating the GIS files, `corine` and `GEBCO`, it must be verified explicitly that they still agree with specified coordinate reference systems in https://github.com/PyPSA/pypsa-eur/blob/7a18740cfb565b5d83d04387f3a7b35c28fa56cc/scripts/build_renewable_profiles.py#L36-L40 .

**Comment by coroa** [comment]
New versions of the data bundle should be put as a separate zenodo file (see also #60)

**Comment by fneum** [comment]
to be combined with xref #342

**Comment by fneum** [comment]
mostly done over time, e.g. #1027 #936 #924
