### ISSUE TITLE
Ensure assignment of all regions without substation

### ISSUE THREAD

**Issue by daniel-rdt** [PyPSA/pypsa-eur#699]
## Checklist

- [x] I am using the latest [release](https://github.com/PyPSA/pypsa-eur/releases)
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

While building bus regions in `build_bus_regions` some onshore bus regions are filtered out for not having a substation. Fore some clusterings this leads to missing regions later on. They are, however, referenced for bus mapping since they still appear in the network.
This might be the cause for some issues with focus_weights.

Detail:
Here some regions for clustered onshore regions disappear:
https://github.com/PyPSA/pypsa-eur/blob/03e1ed6e7914e9e1c5055b7efc06d64425e2bb49/scripts/cluster_network.py#L437-L443

this is due to some regions that don't have a substation being filtered out here:
https://github.com/PyPSA/pypsa-eur/blob/03e1ed6e7914e9e1c5055b7efc06d64425e2bb49/scripts/build_bus_regions.py#L138

**Comment by fneum** [comment]
@FabianHofmann could you have a look?
