### ISSUE TITLE
Update to pyproj>1.9.6 projection syntax

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#73]
as noted in #72

**Comment by fneum** [comment]
In fact, this issue seems to appear only in `vresutils` with PROJ versions greater then 4 (i.e. PROJ5 and PROJ6). Cf. FRESNA/vresutils#4.

So for this repository necessary changes boil down to including the uptaded version of `vresutils`.

**Comment by FabianHofmann** [comment]
If I see correctly we now have the choice between 

1. Installing vresutils directly from the repo, such as  
 ```
     - git+https://github.com/FRESNA/vresutils.git#egg=vresutils
 ```
 in environment.yaml

2. Releasing a new vresutils version and ensure the version in environment.yaml

Any preference?

**Comment by fneum** [comment]
I think option 2 is better, since this is a major switch from PROJ4 to PROJ6. Also, I think the version should be `0.3` then.
