### ISSUE TITLE
Wrong underwater fraction after clustering

### ISSUE THREAD

**Issue by p-glaum** [PyPSA/pypsa-eur#762]
Currently, in the pypsa-eur the underwater fractions for links are underestimated when clustering is applied. This also leads to lower investment cost for those links.

This is due to the calculation of the underwater fraction in the ```cluster_networks``` script.

## Checklist

- [ ] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [ ] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
<paste here>
```

**Comment by fneum** [comment]
Should be closed via the change in how the clustering works.
