### ISSUE TITLE
add h2 retrofitting functionality to myopic foresight workflow

### ISSUE THREAD

**Issue by daniel-rdt** [PyPSA/pypsa-eur#764]
## Describe the feature you'd like to see

* retrofitting of gas pipelines to h2 pipelines in myopic workflow.
* this necessitates subtracting retrofitted capacities from gas network for next optimization year of planning horizon 
* possible renaming of links for next myopic step
* includes dropping infeasibly small pipelines
* includes amending plotting of h2 network

**Comment by fneum** [comment]
I think this is addressed now. #937 #909
