### ISSUE TITLE
Update conda environment file (fixed version)

### ISSUE THREAD

**Issue by euronion** [PyPSA/pypsa-eur#77]
The `conda` environment file [environment.fixedversions.yaml](https://github.com/PyPSA/pypsa-eur/blob/master/environment.fixedversions.yaml) is in principle a great idea to ensure a working environment for the model to run (due to updates in packages).

## Problems with the current version

1. The version includes the package version with plattform specific build numbers, which causes it to not be x-plattform compatible. --> The environment can not be resolved on some plattforms.

2. I cannot resolve the environment based on this file (with build-numbers removed) on my Linux system (conflicting packages, I cannot find which).

3. The file includes packages manually added without version number.

4. The current version is already many months old.

5. The file is bloated with some packages not required for `PyPSA-EUR`.

## Possible solutions

1. Build numbers
* Can be removed from the current file using e.g. `sed`
```
sed -e 's/\(.*\)\(=.*\)$/\1/' environment.fixedversions.yaml  > environment.fixedversions-no-build.yaml
```
* New versions of the file should be created using the `--no-builds` option
```
conda env export -n pypsa-eur -f pypsa-eur.fixedversions.yaml --no-builds
```

For 2.-5. I can provide my current environment, which seems to work now. this leaves the question whether there are specific wishes for this file (like e.g. to not contain most recent packages), or if it is just supposed to work.

**Comment by fneum** [comment]
addressed in #81
