### ISSUE TITLE
Industrial energy demand may contain negative values

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#797]
I have not tracked it down fully, but for "h2 for industry" I get a small negative energy demands for a few nodes. Probably this is related to some normalization issue.

**Comment by fneum** [comment]
There's the chlor-alkali process, which gives hydrogen as a side product. Can be seen in `industry_sector_ratios.csv`.

**Comment by FabianHofmann** [comment]
Interesting! So no bug/unwanted feature? Please, close if that is the case.

**Comment by fneum** [comment]
Nope, all good.
