### ISSUE TITLE
Cannot start snakemake: https://d1gam3xoknrgr2.cloudfront.net/current/WDPA_Dec2023_Public.zip missing 

### ISSUE THREAD

**Issue by mbongaerts** [PyPSA/pypsa-eur#807]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

I tried to run the test model:
```snakemake -call results/test-elec/networks/elec_s_6_ec_lcopt_Co2L-24H.nc --configfile config/test/config.electricity.yaml```

## Error Message

I few days earlier I was able to fully run this example. Now, I got the following error message:
```
Config file config/config.yaml is extended by additional config specified via the command line.
AssertionError in file /home/user/pypsa-eur-master/rules/retrieve.smk, line 262:
The file does not exist.
  File "/home/user/pypsa-eur-master/Snakefile", line 51, in <module>
  File "/home/user/pypsa-eur-master/rules/retrieve.smk", line 262, in <module>
```

I checked line 262 in `retrieve.smk` and observed it was requesting this link:
[https://d1gam3xoknrgr2.cloudfront.net/current/WDPA_Dec2023_Public.zip](https://d1gam3xoknrgr2.cloudfront.net/current/WDPA_Dec2023_Public.zip)

It turns out this link is no longer available, which explains the `AssertionError `.

**Comment by mbongaerts** [comment]
Solution is to change the link in `retrieve.smk` to:
[https://d1gam3xoknrgr2.cloudfront.net/current/WDPA_Dec2023_Public_csv.zip](https://d1gam3xoknrgr2.cloudfront.net/current/WDPA_Dec2023_Public_csv.zip)

**Comment by euronion** [comment]
Hi there,

Thanks for reporting.

I'm afraid your fix will most probably not work, it might not throw an immediate error, but probably somewhere down the workflow. This should be the correct link:

```
https://d1gam3xoknrgr2.cloudfront.net/current/WDPA_Jan2024_Public.zip
```

It seems that WDPA for Jan 2024 was released ahead of schedule, which is annoying and makes retrieving the data even more complicated.

Keeping this issue open for now if someone else is experiencing the same issue until the 01.01.2024. A fix would require chaging the lines here to not only look a month back, but also forward:

https://github.com/PyPSA/pypsa-eur/blob/64300c26e53881d97b5ac6e0695cb2be2aada1c4/rules/retrieve.smk#L259-L264
