### ISSUE TITLE
Tutorial: Error in rule cluster_network

### ISSUE THREAD

**Issue by matteodefelice** [PyPSA/pypsa-eur#849]
I don't know if this is linked to https://github.com/PyPSA/pypsa-eur/issues/847 but however I prefer opening a separate issue. 
Just trying using the latest `pypsa-eur` on Windows WSL. 
If I try to run the the tutorial with:
```
 snakemake -call results/test-elec/networks/elec_s_6_ec_lcopt_Co2L-24H.nc --configfile config/test/config.electricity.yaml
```
I get:
Config file config/config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                     count
--------------------  -------
add_extra_components        1
cluster_network             1
prepare_network             1
solve_network               1
total                       4

Select jobs to execute...

[Sat Jan  6 20:44:15 2024]
rule cluster_network:
    input: resources/networks/elec_s.nc, resources/regions_onshore_elec_s.geojson, resources/regions_offshore_elec_s.geojson, resources/busmap_elec_s.csv, data/costs_2030.csv
    output: resources/networks/elec_s_6.nc, resources/regions_onshore_elec_s_6.geojson, resources/regions_offshore_elec_s_6.geojson, resources/busmap_elec_s_6.csv, resources/linemap_elec_s_6.csv
    log: logs/test-elec/cluster_network/elec_s_6.log
    jobid: 3
    benchmark: benchmarks/test-elec/cluster_network/elec_s_6
    reason: Missing output files: resources/networks/elec_s_6.nc
    wildcards: simpl=, clusters=6
    resources: tmpdir=/tmp, mem_mb=10000, mem_mib=9537

INFO:pypsa.io:Imported network elec_s.nc has buses, carriers, generators, lines, links, loads, storage_units
WARNING:__main__:Keyword argument feature is only valid for algorithm `hac`. Given feature `solar+onwind-time` will be ignored.
Traceback (most recent call last):
  File "/mnt/c/Users/matte/local_work/pypsa-eur/.snakemake/scripts/tmph0c2ai0z.cluster_network.py", line 535, in <module>
    clustering = clustering_for_n_clusters(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/matte/local_work/pypsa-eur/.snakemake/scripts/tmph0c2ai0z.cluster_network.py", line 402, in clustering_for_n_clusters
    busmap = busmap_for_n_clusters(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/matte/local_work/pypsa-eur/.snakemake/scripts/tmph0c2ai0z.cluster_network.py", line 352, in busmap_for_n_clusters
    n_clusters = distribute_clusters(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/matte/local_work/pypsa-eur/.snakemake/scripts/tmph0c2ai0z.cluster_network.py", line 240, in distribute_clusters
    n_clusters >= len(N) and n_clusters <= N.sum()
                             ^^^^^^^^^^^^^^^^^^^^^
AssertionError: Number of clusters must be 37 <= n_clusters <= 3540 for this selection of countries.
[Sat Jan  6 20:44:22 2024]
Error in rule cluster_network:
    jobid: 3
    input: resources/networks/elec_s.nc, resources/regions_onshore_elec_s.geojson, resources/regions_offshore_elec_s.geojson, resources/busmap_elec_s.csv, data/costs_2030.csv
    output: resources/networks/elec_s_6.nc, resources/regions_onshore_elec_s_6.geojson, resources/regions_offshore_elec_s_6.geojson, resources/busmap_elec_s_6.csv, resources/linemap_elec_s_6.csv
    log: logs/test-elec/cluster_network/elec_s_6.log (check log file(s) for error details)
    conda-env: /mnt/c/Users/matte/local_work/pypsa-eur/.snakemake/conda/a383c630458d2a6718159748444265f5_

RuleException:
CalledProcessError in file /mnt/c/Users/matte/local_work/pypsa-eur/rules/build_electricity.smk, line 509:
Command 'set -euo pipefail;  /home/matteo/miniconda3/envs/pypsa-eur/bin/python3.11 /mnt/c/Users/matte/local_work/pypsa-eur/.snakemake/scripts/tmph0c2ai0z.cluster_network.py' returned non-zero exit status 1.
  File "/mnt/c/Users/matte/local_work/pypsa-eur/rules/build_electricity.smk", line 509, in __rule_cluster_network
  File "/home/matteo/miniconda3/envs/pypsa-eur/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-01-06T204413.498867.snakemake.log
```

FYI, this fails also on Windows.

**Comment by fneum** [comment]
This is likely due to a switch from the tutorial to the standard workflow. In this case, it makes sense to clean the workflow directory with `snakemake -j1 purge`.

> `AssertionError: Number of clusters must be 37 <= n_clusters <= 3540 for this selection of countries.`

Every country/synchronous zone needs at least one node.

**Comment by matteodefelice** [comment]
Ì have tried on a new cloned repository and it worked, thanks for this.
