### ISSUE TITLE
TypeError: 'MultiPolygon' object is not iterable (Shapely >=2.0.0)

### ISSUE THREAD

**Issue by mbongaerts** [PyPSA/pypsa-eur#852]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Using shapely >= 2.0.0 results in the error `TypeError: 'MultiPolygon' object is not iterable`.

## Error Message

```
Traceback (most recent call last):
  File "/home/user/pypsa-eur-master/.snakemake/scripts/tmp77kjk9tq.build_shapes.py", line 276, in <module>
    geometry=[country_cover(country_shapes, offshore_shapes.geometry)]
  File "/home/user/pypsa-eur-master/.snakemake/scripts/tmp77kjk9tq.build_shapes.py", line 170, in country_cover
    europe_shape = max(europe_shape, key=attrgetter("area"))
TypeError: 'MultiPolygon' object is not iterable
[Mon Jan  8 10:50:29 2024]
Error in rule build_shapes:
    jobid: 12
    input: data/bundle/naturalearth/ne_10m_admin_0_countries.shp, data/bundle/eez/World_EEZ_v8_2014.shp, data/bundle/NUTS_2013_60M_SH/data/NUTS_RG_60M_2013.shp, data/bundle/nama_10r_3popgdp.tsv.gz, data/bundle/nama_10r_3gdp.tsv.gz, data/bundle/ch_cantons.csv, data/bundle/je-e-21.03.02.xls
    output: resources/default-2/country_shapes.geojson, resources/default-2/offshore_shapes.geojson, resources/default-2/europe_shape.geojson, resources/default-2/nuts3_shapes.geojson
    log: logs/default-2/build_shapes.log (check log file(s) for error details)
    conda-env: /home/user/pypsa-eur-master/.snakemake/conda/344f800c8696b10218d534b2620e7bff_

```
shapely=2.0.2 was installed

## Possible solution?

In `scripts/build_shapes.py` change lines https://github.com/PyPSA/pypsa-eur/blob/799ed069405186f4b88ea6a7cdf9030e6c02c29d/scripts/build_shapes.py#L160-L161:

to :
```
    if isinstance(europe_shape, MultiPolygon):
        shapes =  list(europe_shape.geoms)  
        max_area = max([el.area for el in shapes]) 
        europe_shape = [el for el in shapes if el.area == max_area][0]

```
This seems to solve the problem. However, I am not the author of this script, and I am not sure this implementation is correct?
Thanks for the help!

**Comment by fneum** [comment]
Hi @mbongaerts, the latest CI seems to have no problems with shapely=2.0.2. Does your configuration file specify a subset of countries, or more generally, where does your configuration deviate from the default?

**Comment by mbongaerts** [comment]
Hi @fneum, indeed I did use a subset `countries: ['FR', 'GB', 'NL','BE','NO']`. But it looks like this issue has been mentioned by others as well: https://stackoverflow.com/questions/76074394/typeerror-multipolygon-object-is-not-iterable . Yet, I am not sure if the version of Shapely is the main reason for this issue then (?).

**Comment by coroa** [comment]
Well you probably get a multipolygon as `europe_shape` here, if the countries you choose are not contiguous.

The straightforward translation of the code for shapely 2.0 (also according to its [migration guide](https://shapely.readthedocs.io/en/stable/migration.html#multi-part-geometries-will-no-longer-be-sequences-length-iterable-indexable) is

```
 if isinstance(europe_shape, MultiPolygon): 
     europe_shape = max(europe_shape.geoms, key=attrgetter("area")) 
```

**Comment by coroa** [comment]
But it warrants quickly testing why there is a `MultiPolygon` in the first place, since your list of countries should in principle be contiguous and i'd like to know what is being thrown away here.
