### ISSUE TITLE
Replace OCGT and CCGT with natural gas as conventional carriers

### ISSUE THREAD

**Issue by millingermarkus** [PyPSA/pypsa-eur#855]
OCGT and CCGT are not energy carriers like the other carriers, and can be run both with fossil and renewable methane (PtG or biomethane). Could be replaced by "natural gas" (or "fossil methane") in the listing of conventional carriers. This would have the benefit of adding the ability to easily switch off all fossil fuels.

**Comment by millingermarkus** [comment]
Now added a pull request #1133  to exclude fossil fuels, addressing the "added benefit".

**Comment by fneum** [comment]
closed via #1133?
