### ISSUE TITLE
District heating share is not handled correctly with multiple nodes per country

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/pypsa-eur#860]
This is an ugly bug: for some reason `data/district_share.csv` is passed to `energy_totals.csv` first. Then it is distributed over the nodes to `population_weighted_energy_totals.csv` thereby reducing the share according to the number of nodes. E.g. a country with 10% DH share and 5 nodes with equal populations gets 2% DH share. Really the `district_share.csv` should be handled differently. It may need to be nodal in future.

**Comment by nworbmot** [comment]
It is fixed in this commit (not yet merged): https://github.com/PyPSA/pypsa-eur/commit/6417c7a122954a08bd83af1fd639ea160510c864.

**Comment by fneum** [comment]
closed via #884
