### ISSUE TITLE
Regression caused by powerplantmatching 0.5.9

### ISSUE THREAD

**Issue by koen-vg** [PyPSA/pypsa-eur#887]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

It looks like https://github.com/PyPSA/powerplantmatching/issues/144 has made it into the release of powerplantmatching 0.5.9. It causes the following error for me in pypsa-eur:
```
ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "/home/koen/[...]/.snakemake/scripts/tmp9n0bt3xr.build_powerplants.py", line 213, in <module>
    ppl = map_country_bus(ppl, substations)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koen/[...]/lib/python3.11/site-packages/powerplantmatching/export.py", line 105, in map_country_bus
    res.append(map_bus(df.query("Country == @c"), buses.query("country == @c")))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koen/[...]/lib/python3.11/site-packages/powerplantmatching/export.py", line 78, in map_bus
    return df.assign(bus=buses_i[kdtree.query(df[["lon", "lat"]].values)[1]])
                         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koen/[...]/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5412, in __getitem__
    result = getitem(key)
             ^^^^^^^^^^^^
IndexError: index 644 is out of bounds for axis 0 with size 644
```

I would suggest excluding version 0.5.9 in the environment, i.e. `- powerplantmatching>=0.5.5,!=0.5.9` is working for me. Can open a trivial PR if wanted.

**Comment by fneum** [comment]
Thanks @koen-vg and sorry for causing trouble.

It's fixed here 9f055586

And will also be reverted upstream with next point release of powerplantmatching: https://github.com/PyPSA/powerplantmatching/pull/145
