### ISSUE TITLE
Error in rule build_hydro_profile

### ISSUE THREAD

**Issue by JanFrederickUnnewehr** [PyPSA/pypsa-eur#91]
Hi, I freshly installed pypsa-eur this morning. When executing the rule build_hydro_profile I got the following error message:

```
rule build_hydro_profile:
    input: resources/country_shapes.geojson, data/bundle/EIA_hydro_generation_2000_2014.csv, cutouts/europe-2013-era5
    output: resources/profile_hydro.nc
    jobid: 14
    resources: mem=5000

Traceback (most recent call last):
  File "/home/freddy/Dokumente/pypsa-eur/.snakemake/scripts/tmp7idfj4vt.build_hydro_profile.py", line 70, in <module>
    logger.basicConfig(level=snakemake.config['logging_level'])
AttributeError: 'Logger' object has no attribute 'basicConfig'
[Thu Nov  7 15:43:24 2019]
Error in rule build_hydro_profile:
    jobid: 14
    output: resources/profile_hydro.nc

RuleException:
CalledProcessError in line 164 of /home/freddy/Dokumente/pypsa-eur/Snakefile:
Command 'set -euo pipefail;  /home/freddy/anaconda3/envs/pypsa-eur_47/bin/python3.7 /home/freddy/Dokumente/pypsa-eur/.snakemake/scripts/tmp7idfj4vt.build_hydro_profile.py' returned non-zero exit status 1.
  File "/home/freddy/Dokumente/pypsa-eur/Snakefile", line 164, in __rule_build_hydro_profile
  File "/home/freddy/anaconda3/envs/pypsa-eur_47/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
```

In build_hydro_profile.py I have changed in line 66:
from:`logger.basicConfig(level=snakemake.config['logging_level'])`
to: `logging.basicConfig(level=snakemake.config['logging_level'])`

solved the problem, but I'm not sure about logger handling, because the error occurred in line 70 and not in line 66.

**Comment by fneum** [comment]
Thanks, well spotted. This slipped through when creating the documentation.
The difference in line numbers is just due to the headers snakemake adds to the python scripts.

**Comment by JanFrederickUnnewehr** [comment]
Be happy to do it, sorry that I could not contributed too the documentation so far. The documentation is well done =) very good work!
