### ISSUE TITLE
n.plot() of the EU network shows a node in Africa and all EU nodes linking to it

### ISSUE THREAD

**Issue by bili-tufli** [PyPSA/pypsa-eur#915]
## Checklist

- 'I have created an environment using environment.yaml. I'm testing Pypsa on this dataset: https://zenodo.org/records/6420838`.

## Describe the Bug

*n.plot() of the EU network shows the EU network plus a random node in Africa and all EU nodes linking to it.*
Am I using the wrong Pypsa version? 

## Error Message

* There is no error message 
```
<n.plot()>
```

**Comment by bili-tufli** [comment]
![image](https://github.com/PyPSA/pypsa-eur/assets/68376809/b8f4915a-ae86-4acf-b6e2-ce02d520d92f)

**Comment by fneum** [comment]
It's all buses which do not have a location, defaulting to (0, 0).

Should look better soon with: https://github.com/PyPSA/pypsa-eur/pull/913
