### ISSUE TITLE
Add config.default.yaml at top of Snakefile

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/pypsa-eur#919]
... and use config.yaml only for relative changes. Sort of the same as done in the ariadne repo. 

This would ease keeping and updating a `config.yaml` from previous versions of pypsa-eur.  We could also remove all the `.get` calls in the smk files for the config keys as we ensure that there is always a complete config in the background.

**Comment by fneum** [comment]
Yes, I like that in `pypsa-ariadne` very much!
