### ISSUE TITLE
biogas upgrading costs should be adjusted to new technology data

### ISSUE THREAD

**Issue by lisazeyen** [PyPSA/pypsa-eur#927]
VOM and investment should be multiplied with the efficiency since the new data is in unit output.
## Checklist

- [ ] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [ ] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
<paste here>
```

**Comment by fneum** [comment]
I double-checked this and in principle you're right, but since the efficiency is 1 I think it is justified to skip this.
