### ISSUE TITLE
increase default rooftop PV capacities

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#935]
@Parisra can you add the source you mentioned?

**Comment by Parisra** [comment]
The current potential for rooftop PV (504 GW, or 554 TWh/a) in EU is a good estimate (as discussed before [here](https://github.com/PyPSA/pypsa-eur/issues/544) and based on multiple sources like [here](https://www.sciencedirect.com/science/article/pii/S0038092X12002186#:~:text=The%20modelling%20results%20indicate%20that,increase%20of%2030%25%20by%202060.) and [here](https://www.sciencedirect.com/science/article/pii/S1364032119305179?ref=pdf_download&fr=RR-2&rr=8718d2afad23be38)), but there is room for increasing the potential, especially as solar PV is becoming extremely cheap, and more and more people are interested in having an independent power supply.

Sources that estimate a higher rooftop PV potential for EU:
[[1](https://www.researchgate.net/publication/323918094_The_Rooftop_Potential_for_PV_Systems_in_the_European_Union_to_deliver_the_Paris_Agreement)] : Estimates 1500 TWh for EU
[[2](https://www.sciencedirect.com/science/article/pii/S2211467X19300811#bib28)]: Estimates 4800 TWh for EU by estimating potential for Switzerland based on satellite imagery and correlating it to the whole EU (there is no distinction made between residential or commercial buildings). Based on a quick comparison of their potential for each country with the current assumed potential in pypsa-eur, each country’s potential could at least be multiplied by 5 if we were to use their estimates:
![image](https://github.com/PyPSA/pypsa-eur/assets/102019906/58414c74-8e1d-4f37-9f45-bfc3c78b3fe5)

Some studies have also assessed national potentials of roof-mounted PV, e.g. 1262 TWh/a [[3](https://www.volker-quaschning.de/downloads/Klima2000.pdf)] for Germany, which is higher than our assumption for the entire EU. 

As for the EU’s current targets, the [2022 Solar Energy Strategy](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=COM%3A2022%3A108%3AFIN) sets a target to bring online 385 GWp by 2025 and 720 GWp of PV installed capacity (already larger than 500 GW) in the EU by 2030. A recent communication for EU commission [[Communication on the potential of applied PV in the European Union: Rooftops, reservoirs, roads (R3)](https://www.epj-pv.org/articles/epjpv/full_html/2024/01/pv230071/pv230071.html)] is also estimating a 1 TW potential for rooftop PV in EU by using new PV technology and placing it along the roads and railways.

Based on all this. I think doubling the current potential (or even tripling it) is justified  ( @martavp could also give a more expert opinion here). 

Note 1: There is also a lot of ongoing research using satellite imagery and machine learning to try and estimate rooftop installed capacity (one [here](https://www.cell.com/joule/pdf/S2542-4351(18)30570-1.pdf) estimated all the installed PV in US). If such a study happens for EU, we could use it for rooftop brownfield assumptions.

Note 2: If the grid connection cost for solar utility in pypsa-eur is enabled, rooftop PV will effectively be cheaper than utility PV, and all the capacity will be installed.
