### ISSUE TITLE
Myopic path unfeasible with default config file due to oil balances

### ISSUE THREAD

**Issue by martavp** [PyPSA/pypsa-eur#945]
With the current default config file, Fischer-Tropsch is installed in 2040 (due to the combination of the assumptions for exogenous use of oil in land_transport in shipping together with the stringent co2_limit for that year).

In 2050, the minimum operation requirement of Fischer-Tropsch produces a certain amount of oil that is higher than the oil demand (since land transport and shipping are assumed to be fully electrified/converted to methanol by 2050). 

A simple fix could be to make [min_part_load_fischer_tropsch](https://github.com/PyPSA/pypsa-eur/blob/66d078e4074986800c61e1df66d33b804a04782c/config/config.default.yaml#L530)=0 in the default config file or we change the other default assumptions for oil demand in land transport and shipping. I think a working default config for the myopic option is always good for new users. 

This is similar to the issue fixed in https://github.com/PyPSA/pypsa-eur/pull/791/files
Maybe you have some thoughts on this @lisazeyen ?

**Comment by lisazeyen** [comment]
One option is to set the `min_part_load_fischer_tropsch` to zero. I was at a conference where they were basically saying that the process is as flexible as an electrolysis. The other options is to allow Fischer-Tropsch to be built back (not to fix the capacity) and add some extra costs at the end for stranded assets. One of our master students @daniel-rdt was implementing that I think here https://github.com/daniel-rdt/pypsa-eur/tree/feature/FT_build_back

**Comment by fneum** [comment]
I reduced the FT min part load to 50% in `27a6f619` as a compromise, which should be sufficient to make feasible but retain the sunk cost of FT capacity. I was a bit reluctant to follow @daniel-rdt and change the `capital_cost` to a negative value which creates inconsistencies when building total system costs. Let me know if this is not sufficient.
