### ISSUE TITLE
Documentation for 'all' wildcards

### ISSUE THREAD

**Issue by euronion** [PyPSA/pypsa-eur#99]
The [documentation](https://pypsa-eur.readthedocs.io/en/latest/wildcards.html#the-simpl-wildcard) is missing a description for the `all` wildcards in the snakemake workflow.

E.g. what do the options `{ll} = lall, lvall, lcall` do.

As far as I can tell this concerns the wildcards `{ll}, {clusters}, {simpl}`.

**Comment by fneum** [comment]
will be abolished
